# 04 Peak Annotation

## Initialize

In [1]:
# Load Libraries
library(ChIPseeker)
library(GenomicFeatures)
library(dplyr)
library(tidyr)

# Move to working directory
setwd("/home/dalbao/AlbaoRunx3Manuscript/cutnrun")

# Make folder if it does not exist
if (!dir.exists("04_peakAnnotation")) {
    dir.create("04_peakAnnotation", recursive = TRUE)
}

ChIPseeker v1.42.0 Learn more at https://yulab-smu.top/contribution-knowledge-mining/

Please cite:

Guangchuang Yu, Li-Gen Wang, and Qing-Yu He. ChIPseeker: an
R/Bioconductor package for ChIP peak annotation, comparison and
visualization. Bioinformatics. 2015, 31(14):2382-2383

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, saveRDS, setdiff,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: GenomicRanges

Loading required package: AnnotationDbi

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘dplyr’


The following object is masked from ‘package:AnnotationDbi’:

    select


The following object is masked from ‘package:Biobase’:

    combine


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘tidyr’


The following object is masked from ‘package:S4Vectors’:

    expand

## Import GTF Data

In [2]:
# Create a TxDb object for annotations 
txdb <- makeTxDbFromGFF("source_data/genes.gtf", format = "gtf") # GRCm38

Warning message in call_fun_in_txdbmaker("makeTxDbFromGFF", ...):
“makeTxDbFromGFF() has moved to the txdbmaker package. Please call
  txdbmaker::makeTxDbFromGFF() to get rid of this warning.”
Import genomic features from the file as a GRanges object ...
OK

Prepare the 'metadata' data frame ...
OK

Make the TxDb object ...
Warning message in .get_cds_IDX(mcols0$type, mcols0$phase):
“The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.”
OK

## Annotate Peaks with Flanks

In [3]:
# Annotate peaks
peaks <- annotatePeak(
    peak = "01_peakEDA/fullpeak.clean.clustered.named.bed",
    tssRegion = c(-3000, 3000),     # Region to consider as TSS proximal
    TxDb = txdb,                    # Ensembl TxDb for GRCm38
    addFlankGeneInfo = TRUE,        # Add gene information
    flankDistance = 150000          # Distance to consider as gene body
)

>> loading peak file...				 2026-07-22 02:04:53
>> preparing features information...		 2026-07-22 02:04:54
>> identifying nearest features...		 2026-07-22 02:04:54
>> calculating distance from peak to TSS...	 2026-07-22 02:04:54
>> assigning genomic annotation...		 2026-07-22 02:04:54
>> adding flank feature information from peaks...	 2026-07-22 02:05:03
>> assigning chromosome lengths			 2026-07-22 02:05:05
>> done...					 2026-07-22 02:05:05

In [4]:
peaks

Annotated peaks generated by ChIPseeker
4172/4172  peaks were annotated
Genomic Annotation Summary:
              Feature   Frequency
9    Promoter (<=1kb) 52.44487057
10   Promoter (1-2kb)  4.02684564
11   Promoter (2-3kb)  2.99616491
4              5' UTR  0.09587728
3              3' UTR  1.17449664
1            1st Exon  0.04793864
7          Other Exon  1.65388303
2          1st Intron  7.62224353
8        Other Intron 10.61840844
6  Downstream (<=300)  0.16778523
5   Distal Intergenic 19.15148610

In [5]:
peaks <- as.data.frame(peaks)
head(peaks)

  seqnames start    end      width strand V4               V5
1 1         7397451  7398450 1000  *      shRunx3_Runx1_5  cluster_2
2 1         9847901  9848700  800  *      shCd19_Runx1_27  cluster_2
3 1        10037651 10038650 1000  *      shCd19_Runx3_1   cluster_1
4 1        13371951 13373200 1250  *      shCd19_Runx3_2   cluster_2
5 1        13374001 13374750  750  *      shCd19_Runx1_46  cluster_2
6 1        13382101 13382950  850  *      shRunx3_Runx3_33 cluster_2
  annotation                                                    geneChr
1 Promoter (<=1kb)                                              29
2 Promoter (<=1kb)                                              29
3 Promoter (<=1kb)                                              29
4 Promoter (<=1kb)                                              29
5 Promoter (<=1kb)                                              29
6 Intron (ENSMUST00000185813/ENSMUSG00000101476, intron 1 of 1) 29
  geneStart geneEnd  geneLength geneStrand geneId
1  7349406   7397801  48396     2          ENSMUSG00000097797
2  9848272   9900843  52572     1          ENSMUSG00000025915
3 10024601  10038127  13527     2          ENSMUSG00000025917
4 13139105  13372439 233335     2          ENSMUSG00000005886
5 13139159  13374083 234925     2          ENSMUSG00000005886
6 13376070  13388413  12344     1          ENSMUSG00000101476
  transcriptId       distanceToTSS
1 ENSMUST00000181554    0
2 ENSMUST00000171265    0
3 ENSMUST00000027050    0
4 ENSMUST00000081713    0
5 ENSMUST00000068304    0
6 ENSMUST00000185813 6031
  flank_txIds
1 ENSMUST00000104056;ENSMUST00000181554;ENSMUST00000193106;ENSMUST00000193732;ENSMUST00000193428;ENSMUST00000192649;ENSMUST00000194886;ENSMUST00000193998
2 ENSMUST00000088658;ENSMUST00000115468;ENSMUST00000188212;ENSMUST00000166384;ENSMUST00000188782;ENSMUST00000168907;ENSMUST00000188625;ENSMUST00000188738;ENSMUST00000188298;ENSMUST00000171265;ENSMUST00000188830;ENSMUST00000189050;ENSMUST00000097826;ENSMUST00000191338;ENSMUST00000188486;ENSMUST00000147000;ENSMUST00000124874;ENSMUST00000027049;ENSMUST00000130102;ENSMUST00000176398;ENSMUST00000155163;ENSMUST00000057438;ENSMUST00000052843;ENSMUST00000171802;ENSMUST00000125294;ENSMUST00000140948;ENSMUST00000118098;ENSMUST00000183059;ENSMUST00000063059;ENSMUST00000134692;ENSMUST00000158291;ENSMUST00000175437;ENSMUST00000181821;ENSMUST00000181358;ENSMUST00000191287;ENSMUST00000189431;ENSMUST00000189322;ENSMUST00000182580;ENSMUST00000182819;ENSMUST00000182043;ENSMUST00000182498;ENSMUST00000182742;ENSMUST00000185184;ENSMUST00000097824;ENSMUST00000192299
3 ENSMUST00000166384;ENSMUST00000188782;ENSMUST00000168907;ENSMUST00000188738;ENSMUST00000188298;ENSMUST00000171265;ENSMUST00000097826;ENSMUST00000191338;ENSMUST00000188486;ENSMUST00000147000;ENSMUST00000124874;ENSMUST00000027049;ENSMUST00000130102;ENSMUST00000176398;ENSMUST00000155163;ENSMUST00000027050;ENSMUST00000190155;ENSMUST00000186528;ENSMUST00000188619;ENSMUST00000139578;ENSMUST00000150509;ENSMUST00000191296;ENSMUST00000052843;ENSMUST00000171802;ENSMUST00000125294;ENSMUST00000140948;ENSMUST00000118098;ENSMUST00000183059;ENSMUST00000190610;ENSMUST00000191012;ENSMUST00000071087;ENSMUST00000143606;ENSMUST00000191360;ENSMUST00000117415;ENSMUST00000191521;ENSMUST00000118263;ENSMUST00000122156;ENSMUST00000190063;ENSMUST00000119714;ENSMUST00000134716;ENSMUST00000155974;ENSMUST00000186294;ENSMUST00000149214;ENSMUST00000190318;ENSMUST00000188249;ENSMUST00000153804;ENSMUST00000188449;ENSMUST00000123261;ENSMUST00000185422;ENSMUST00000190625;ENSMUST00000187226;ENSMUST00000136283;ENSMUST00000128164;ENSMUST00000136898;ENSMUST00000148663;ENSMUST00000088615;ENSMUST00000187417;ENSMUST00000142497;ENSMUST00000156563;ENSMUST00000128834;ENSMUST00000131556;ENSMUST00000134692;ENSMUST00000157528;ENSMUST00000175437;ENSMUST00000179194;ENSMUST00000182580;ENSMUST00000182819;ENSMUST00000182043;ENSMUST00000182498;ENSMUST00000182742;ENSMUST00000185184;ENSMUST00000097824;ENSMUST00000194474;ENSMUST00000192299
4 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
5 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
6 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
  flank_geneIds
1 ENSMUSG00000077244;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000102768;ENSMUSG00000103067;ENSMUSG00000103498
2 ENSMUSG00000025912;ENSMUSG00000025912;ENSMUSG00000025912;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000045210;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046334;ENSMUSG00000087199;ENSMUSG00000088916;ENSMUSG00000093178;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000099032;ENSMUSG00000099032;ENSMUSG00000104025
3 ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000087199;ENSMUSG00000088153;ENSMUSG00000093178;ENSMUSG00000095780;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000099032;ENSMUSG00000099032;ENSMUSG00000102356;ENSMUSG00000104025
4 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
5 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
6 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
  flank_gene_distances
1 131648;0;0;0;-16062;82000;-99518;-12229
2 -147692;-147877;-148247;0;0;0;49743;0;0;0;0;0;0;-34767;-46727;136992;154753;160436;160430;160430;160430;-99519;-59938;-59938;-59968;-59970;-62614;-83420;-45348;-133687;-13299;93849;100253;99945;99420;99314;64123;95418;94523;94197;95403;95417;119232;114109;-118614
3 0;0;0;0;0;0;0;154184;142224;-51959;-34198;-28515;-28521;-28521;-28521;0;-2523;0;0;0;0;0;129013;129013;128983;128981;126337;105531;0;0;0;0;0;0;-1117;-1123;-1123;-1127;-1135;-1173;-1505;-7843;-18274;-32533;-35732;-36210;-36263;-49097;-57214;-65578;-74226;-76775;-87334;-91309;-95320;194020;103051;115880;121410;122656;194020;55264;-127889;-95102;-27734;-93533;-94428;-94754;-93548;-93534;-69719;-74842;19294;70337
4 0;0;0;0;0;0;0;-72229;-37342;109753;34455;0;-81445;-15221;-23747;-135517;-73044
5 0;0;0;0;0;0;0;-74279;-39392;111803;32905;0;-83495;-17271;-25797;-137567;-75094
6 0;0;0;0;0;0;0;-82379;-47492;119903;24705;0;-91595;-25371;-33897;-145667;-83194

In [6]:
head(peaks[,1:16])

  seqnames start    end      width strand V4               V5
1 1         7397451  7398450 1000  *      shRunx3_Runx1_5  cluster_2
2 1         9847901  9848700  800  *      shCd19_Runx1_27  cluster_2
3 1        10037651 10038650 1000  *      shCd19_Runx3_1   cluster_1
4 1        13371951 13373200 1250  *      shCd19_Runx3_2   cluster_2
5 1        13374001 13374750  750  *      shCd19_Runx1_46  cluster_2
6 1        13382101 13382950  850  *      shRunx3_Runx3_33 cluster_2
  annotation                                                    geneChr
1 Promoter (<=1kb)                                              29
2 Promoter (<=1kb)                                              29
3 Promoter (<=1kb)                                              29
4 Promoter (<=1kb)                                              29
5 Promoter (<=1kb)                                              29
6 Intron (ENSMUST00000185813/ENSMUSG00000101476, intron 1 of 1) 29
  geneStart geneEnd  geneLength geneStrand geneId
1  7349406   7397801  48396     2          ENSMUSG00000097797
2  9848272   9900843  52572     1          ENSMUSG00000025915
3 10024601  10038127  13527     2          ENSMUSG00000025917
4 13139105  13372439 233335     2          ENSMUSG00000005886
5 13139159  13374083 234925     2          ENSMUSG00000005886
6 13376070  13388413  12344     1          ENSMUSG00000101476
  transcriptId       distanceToTSS
1 ENSMUST00000181554    0
2 ENSMUST00000171265    0
3 ENSMUST00000027050    0
4 ENSMUST00000081713    0
5 ENSMUST00000068304    0
6 ENSMUST00000185813 6031

In [7]:
# Is V4 (ID) unique?
length(unique(peaks$V4)) == nrow(peaks) # TRUE

[1] TRUE

## Convert EnsemblIDs to Gene Symbols+

In [8]:
# Load EnsemblID conversion
ensembl2symbol <- read.table("source_data/ensembl_102.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)
colnames(ensembl2symbol) <- c("GeneID", "GeneSymbol")

# Check df
head(ensembl2symbol)

  GeneID             GeneSymbol
1 ENSMUSG00000064372 mt-Tp
2 ENSMUSG00000064371 mt-Tt
3 ENSMUSG00000064370 mt-Cytb
4 ENSMUSG00000064369 mt-Te
5 ENSMUSG00000064368 mt-Nd6
6 ENSMUSG00000064367 mt-Nd5

In [9]:
# Function to convert EnsemblIDs to GeneSymbols
convert_ids <- function(ids, conversion_df) {
    sapply(ids, function(id) {
        id_list <- unlist(strsplit(id, ";"))
        symbol_list <- sapply(id_list, function(single_id) {
            symbol <- conversion_df$GeneSymbol[conversion_df$GeneID == single_id]
            if (length(symbol) == 0 || is.na(symbol[1]) || symbol[1] == "") {
                return(single_id)
            } else {
                return(symbol)
            }
        })
        paste(symbol_list, collapse = ";")
    })
}

In [10]:
# Keep only items in ensemble2symbol that are in peak_anno_df
uniqueids <- unique(unlist(strsplit(peaks$flank_geneIds, ";")))
uniqueids <- unique(c(uniqueids, peaks$flank_geneId))

ensembl2symbol <- ensembl2symbol[ensembl2symbol$GeneID %in% uniqueids, ]

In [11]:
# Convert geneId and flank_geneIds columns
peaks$geneSymbol <- convert_ids(peaks$geneId, ensembl2symbol)
peaks$flank_geneSymbols <- convert_ids(peaks$flank_geneIds, ensembl2symbol)
print("Done Annotation")

[1] "Done Annotation"

In [12]:
head(peaks)

  seqnames start    end      width strand V4               V5
1 1         7397451  7398450 1000  *      shRunx3_Runx1_5  cluster_2
2 1         9847901  9848700  800  *      shCd19_Runx1_27  cluster_2
3 1        10037651 10038650 1000  *      shCd19_Runx3_1   cluster_1
4 1        13371951 13373200 1250  *      shCd19_Runx3_2   cluster_2
5 1        13374001 13374750  750  *      shCd19_Runx1_46  cluster_2
6 1        13382101 13382950  850  *      shRunx3_Runx3_33 cluster_2
  annotation                                                    geneChr
1 Promoter (<=1kb)                                              29
2 Promoter (<=1kb)                                              29
3 Promoter (<=1kb)                                              29
4 Promoter (<=1kb)                                              29
5 Promoter (<=1kb)                                              29
6 Intron (ENSMUST00000185813/ENSMUSG00000101476, intron 1 of 1) 29
  geneStart ⋯ geneLength geneStrand geneId             transcriptId
1  7349406  ⋯  48396     2          ENSMUSG00000097797 ENSMUST00000181554
2  9848272  ⋯  52572     1          ENSMUSG00000025915 ENSMUST00000171265
3 10024601  ⋯  13527     2          ENSMUSG00000025917 ENSMUST00000027050
4 13139105  ⋯ 233335     2          ENSMUSG00000005886 ENSMUST00000081713
5 13139159  ⋯ 234925     2          ENSMUSG00000005886 ENSMUST00000068304
6 13376070  ⋯  12344     1          ENSMUSG00000101476 ENSMUST00000185813
  distanceToTSS
1    0
2    0
3    0
4    0
5    0
6 6031
  flank_txIds
1 ENSMUST00000104056;ENSMUST00000181554;ENSMUST00000193106;ENSMUST00000193732;ENSMUST00000193428;ENSMUST00000192649;ENSMUST00000194886;ENSMUST00000193998
2 ENSMUST00000088658;ENSMUST00000115468;ENSMUST00000188212;ENSMUST00000166384;ENSMUST00000188782;ENSMUST00000168907;ENSMUST00000188625;ENSMUST00000188738;ENSMUST00000188298;ENSMUST00000171265;ENSMUST00000188830;ENSMUST00000189050;ENSMUST00000097826;ENSMUST00000191338;ENSMUST00000188486;ENSMUST00000147000;ENSMUST00000124874;ENSMUST00000027049;ENSMUST00000130102;ENSMUST00000176398;ENSMUST00000155163;ENSMUST00000057438;ENSMUST00000052843;ENSMUST00000171802;ENSMUST00000125294;ENSMUST00000140948;ENSMUST00000118098;ENSMUST00000183059;ENSMUST00000063059;ENSMUST00000134692;ENSMUST00000158291;ENSMUST00000175437;ENSMUST00000181821;ENSMUST00000181358;ENSMUST00000191287;ENSMUST00000189431;ENSMUST00000189322;ENSMUST00000182580;ENSMUST00000182819;ENSMUST00000182043;ENSMUST00000182498;ENSMUST00000182742;ENSMUST00000185184;ENSMUST00000097824;ENSMUST00000192299
3 ENSMUST00000166384;ENSMUST00000188782;ENSMUST00000168907;ENSMUST00000188738;ENSMUST00000188298;ENSMUST00000171265;ENSMUST00000097826;ENSMUST00000191338;ENSMUST00000188486;ENSMUST00000147000;ENSMUST00000124874;ENSMUST00000027049;ENSMUST00000130102;ENSMUST00000176398;ENSMUST00000155163;ENSMUST00000027050;ENSMUST00000190155;ENSMUST00000186528;ENSMUST00000188619;ENSMUST00000139578;ENSMUST00000150509;ENSMUST00000191296;ENSMUST00000052843;ENSMUST00000171802;ENSMUST00000125294;ENSMUST00000140948;ENSMUST00000118098;ENSMUST00000183059;ENSMUST00000190610;ENSMUST00000191012;ENSMUST00000071087;ENSMUST00000143606;ENSMUST00000191360;ENSMUST00000117415;ENSMUST00000191521;ENSMUST00000118263;ENSMUST00000122156;ENSMUST00000190063;ENSMUST00000119714;ENSMUST00000134716;ENSMUST00000155974;ENSMUST00000186294;ENSMUST00000149214;ENSMUST00000190318;ENSMUST00000188249;ENSMUST00000153804;ENSMUST00000188449;ENSMUST00000123261;ENSMUST00000185422;ENSMUST00000190625;ENSMUST00000187226;ENSMUST00000136283;ENSMUST00000128164;ENSMUST00000136898;ENSMUST00000148663;ENSMUST00000088615;ENSMUST00000187417;ENSMUST00000142497;ENSMUST00000156563;ENSMUST00000128834;ENSMUST00000131556;ENSMUST00000134692;ENSMUST00000157528;ENSMUST00000175437;ENSMUST00000179194;ENSMUST00000182580;ENSMUST00000182819;ENSMUST00000182043;ENSMUST00000182498;ENSMUST00000182742;ENSMUST00000185184;ENSMUST00000097824;ENSMUST00000194474;ENSMUST00000192299
4 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
5 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
6 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
  flank_geneIds
1 ENSMUSG00000077244;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000102768;ENSMUSG00000103067;ENSMUSG00000103498
2 ENSMUSG00000025912;ENSMUSG00000025912;ENSMUSG00000025912;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000045210;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046334;ENSMUSG00000087199;ENSMUSG00000088916;ENSMUSG00000093178;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000099032;ENSMUSG00000099032;ENSMUSG00000104025
3 ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000087199;ENSMUSG00000088153;ENSMUSG00000093178;ENSMUSG00000095780;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000099032;ENSMUSG00000099032;ENSMUSG00000102356;ENSMUSG00000104025
4 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
5 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
6 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
  flank_gene_distances
1 131648;0;0;0;-16062;82000;-99518;-12229
2 -147692;-147877;-148247;0;0;0;49743;0;0;0;0;0;0;-34767;-46727;136992;154753;160436;160430;160430;160430;-99519;-59938;-59938;-59968;-59970;-62614;-83420;-45348;-133687;-13299;93849;100253;99945;99420;99314;64123;95418;94523;94197;95403;95417;119232;114109;-118614
3 0;0;0;0;0;0;0;154184;142224;-51959;-34198;-28515;-28521;-28521;-28521;0;-2523;0;0;0;0;0;129013;129013;128983;128981;126337;105531;0;0;0;0;0;0;-1117;-1123;-1123;-1127;-1135;-1173;-1505;-7843;-18274;-32533;-35732;-36210;-36263;-49097;-57214;-65578;-74226;-76775;-87334;-91309;-95320;194020;103051;115880;121410;122656;194020;55264;-127889;-95102;-27734;-93533;-94428;-94754;-93548;-93534;-69719;-74842;19294;70337
4 0;0;0;0;0;0;0;-72229;-37342;109753;34455;0;-81445;-15221;-23747;-135517;-73044
5 0;0;0;0;0;0;0;-74279;-39392;111803;32905;0;-83495;-17271;-25797;-137567;-75094
6 0;0;0;0;0;0;0;-82379;-47492;119903;24705;0;-91595;-25371;-33897;-145667;-83194
  geneSymbol
1 Gm26901
2 Sgk3
3 Cops5
4 Ncoa2
5 Ncoa2
6 Gm29570
  flank_geneSymbols
1 Gm23274;Gm26901;Gm26901;Gm26901;Gm26901;Gm19002;Gm30414;Gm18984
2 Mybl1;Mybl1;Mybl1;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Vcpip1;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Gm6195;Gm15818;Gm22607;Snord87;1700034P13Rik;1700034P13Rik;1700034P13Rik;1700034P13Rik;1700034P13Rik;Snhg6;Snhg6;Snhg6;Snhg6;Snhg6;Tcf24;Tcf24;E330040D14Rik
3 Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Cops5;Cops5;Cops5;Cops5;Cops5;Cops5;Cops5;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Gm15818;Gm26348;Snord87;Gm24674;Snhg6;Snhg6;Snhg6;Snhg6;Snhg6;Tcf24;Tcf24;1700047N06Rik;E330040D14Rik
4 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702
5 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702
6 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702

## Add Motifs

In [13]:
# Load motif extraction results
motifs <- read.table("03_motif/motifAnnotated.simple.tsv", header = FALSE, sep = "\t", stringsAsFactors = FALSE)
colnames(motifs) <- c("PositionID", "Motif")

head(motifs)

  PositionID         Motif
1 shCd19_Runx3_2657  ETS:RUNX(ETS,Runt),AACGGATGTGGC,-42,+,9.708065
2 shRunx3_Runx3_9075 ETS:RUNX(ETS,Runt),GCAGGATGTGGT,5,+,13.566359
3 shCd19_Runx3_2645  ETS:RUNX(ETS,Runt),GCCACTTCCTGT,66,-,12.502087
4 shRunx3_Runx3_9003 ETS:RUNX(ETS,Runt),ACCACTTCCTCC,-39,-,12.561658
5 shCd19_Runx3_2619  ETS:RUNX(ETS,Runt),CCCACATCCGGG,23,-,9.373720
6 shRunx3_Runx3_8938 ETS:RUNX(ETS,Runt),TGCGGATGTGGG,4,+,8.702796

In [15]:
# Collapse motifs by PositionID
motifs <- motifs %>%
    group_by(PositionID) %>%
    summarise(Motif = paste(unique(Motif), collapse = ";"))

library(stringr)

extract_first_field <- function(x) {
    items <- str_split(x, ";")[[1]]              # split into individual motif entries
    first_fields <- sapply(items, function(i) str_split(i, ",")[[1]][1])  # take first field of each
    paste(first_fields, collapse = ",")
}

motifs <- motifs %>%
  mutate(MotifNames = sapply(Motif, extract_first_field))

head(motifs)

                                                                                                                                                                                                                                 PositionID
Fra1(bZIP),AGGTTAGTCAGC,36,+,7.074330;Fra2(bZIP),GGTTAGTCAGCC,48,-,6.574687;Atf3(bZIP),GGTTAGTCAGCC,37,+,6.385902;Atf3(bZIP),AGGTTAGTCAGC,47,-,6.331743;Fos(bZIP),GGTTAGTCAGCC,48,-,7.403138;AP-1(bZIP),GGTTAGTCAG,46,-,6.203397 late_Runx3_2495
Etv2(ETS),CTGAGGAAGTAG,-88,-,7.518460                                                                                                                                                                                            late_Runx3_2873
RUNX(Runt),GTGTGGTTGT,42,-,6.715326;RUNX2(Runt),CCGTGTGGTTGT,42,-,7.858747;RUNX1(Runt),CGTGTGGTTG,41,-,7.028477                                                                                                                  late_Runx3_3029
STAT5(Stat),CCTTCTTAGAAT,-97,+,9.316957;STAT5(Stat),CTTCTTAGAATT,-85,-,10.212363;STAT1(Stat),CCCTTCTTAGAATT,-98,+,8.062638;STAT1(Stat),CCTTCTTAGAATTG,-84,-,8.140600                                                             late_Runx3_3345
Etv2(ETS),GGCAGGAAGTAT,91,-,8.166438;Etv2(ETS),AGCCGGAAGTGG,63,-,8.211854;ETS1(ETS),GCCGGAAGTG,53,+,10.256266;ETS1(ETS),GCAGGAAGTA,81,+,9.463717;Fli1(ETS),GCAGGAAGTA,90,-,6.576133;Fli1(ETS),GCCGGAAGTG,62,-,7.567547           late_Runx3_3608
Fli1(ETS),AGCGGAAAGG,69,-,5.931610                                                                                                                                                                                               late_Runx3_3825
                                                                                                                                                                                                                                 Motif
Fra1(bZIP),AGGTTAGTCAGC,36,+,7.074330;Fra2(bZIP),GGTTAGTCAGCC,48,-,6.574687;Atf3(bZIP),GGTTAGTCAGCC,37,+,6.385902;Atf3(bZIP),AGGTTAGTCAGC,47,-,6.331743;Fos(bZIP),GGTTAGTCAGCC,48,-,7.403138;AP-1(bZIP),GGTTAGTCAG,46,-,6.203397 Fra1(bZIP),AGGTTAGTCAGC,36,+,7.074330;Fra2(bZIP),GGTTAGTCAGCC,48,-,6.574687;Atf3(bZIP),GGTTAGTCAGCC,37,+,6.385902;Atf3(bZIP),AGGTTAGTCAGC,47,-,6.331743;Fos(bZIP),GGTTAGTCAGCC,48,-,7.403138;AP-1(bZIP),GGTTAGTCAG,46,-,6.203397
Etv2(ETS),CTGAGGAAGTAG,-88,-,7.518460                                                                                                                                                                                            Etv2(ETS),CTGAGGAAGTAG,-88,-,7.518460
RUNX(Runt),GTGTGGTTGT,42,-,6.715326;RUNX2(Runt),CCGTGTGGTTGT,42,-,7.858747;RUNX1(Runt),CGTGTGGTTG,41,-,7.028477                                                                                                                  RUNX(Runt),GTGTGGTTGT,42,-,6.715326;RUNX2(Runt),CCGTGTGGTTGT,42,-,7.858747;RUNX1(Runt),CGTGTGGTTG,41,-,7.028477
STAT5(Stat),CCTTCTTAGAAT,-97,+,9.316957;STAT5(Stat),CTTCTTAGAATT,-85,-,10.212363;STAT1(Stat),CCCTTCTTAGAATT,-98,+,8.062638;STAT1(Stat),CCTTCTTAGAATTG,-84,-,8.140600                                                             STAT5(Stat),CCTTCTTAGAAT,-97,+,9.316957;STAT5(Stat),CTTCTTAGAATT,-85,-,10.212363;STAT1(Stat),CCCTTCTTAGAATT,-98,+,8.062638;STAT1(Stat),CCTTCTTAGAATTG,-84,-,8.140600
Etv2(ETS),GGCAGGAAGTAT,91,-,8.166438;Etv2(ETS),AGCCGGAAGTGG,63,-,8.211854;ETS1(ETS),GCCGGAAGTG,53,+,10.256266;ETS1(ETS),GCAGGAAGTA,81,+,9.463717;Fli1(ETS),GCAGGAAGTA,90,-,6.576133;Fli1(ETS),GCCGGAAGTG,62,-,7.567547           Etv2(ETS),GGCAGGAAGTAT,91,-,8.166438;Etv2(ETS),AGCCGGAAGTGG,63,-,8.211854;ETS1(ETS),GCCGGAAGTG,53,+,10.256266;ETS1(ETS),GCAGGAAGTA,81,+,9.463717;Fli1(ETS),GCAGGAAGTA,90,-,6.576133;Fli1(ETS),GCCGGAAGTG,62,-,7.567547
Fli1(ETS),AGCGGAAAGG,69,-,5.931610                                                                                                                                                                                               Fli1(ETS),AGCGGAAAGG,69,-,5.931610
                                                                                                                                                                                                                                 MotifNames
Fra1(bZIP),AGGTTAGTCAGC,36,+,7.074330;Fra2(bZIP),GGTTAGTCAGCC,48,-,6.574687;Atf3(bZIP),GGTTAGTCAGCC,37,+,6.385902;Atf3(bZIP),AGGTTAGTCAGC,47,-,6.331743;Fos(bZIP),GGTTAGTCAGCC,48,-,7.403138;AP-1(bZIP),GGTTAGTCAG,46,-,6.203397 Fra1(bZIP),Fra2(bZIP),Atf3(bZIP),Atf3(bZIP),Fos(bZIP),AP-1(bZIP)
Etv2(ETS),CTGAGGAAGTAG,-88,-,7.518460                                                                                                                                                                                            Etv2(ETS)
RUNX(Runt),GTGTGGTTGT,42,-,6.715326;RUNX2(Runt),CCGTGTGGTTGT,42,-,7.858747;RUNX1(Runt),CGTGTGGTTG,41,-,7.028477                                                                                                                  RUNX(Runt),RUNX2(Runt),RUNX1(Runt)
STAT5(Stat),CCTTCTTAGAAT,-97,+,9.316957;STAT5(Stat),CTTCTTAGAATT,-85,-,10.212363;STAT1(Stat),CCCTTCTTAGAATT,-98,+,8.062638;STAT1(Stat),CCTTCTTAGAATTG,-84,-,8.140600                                                             STAT5(Stat),STAT5(Stat),STAT1(Stat),STAT1(Stat)
Etv2(ETS),GGCAGGAAGTAT,91,-,8.166438;Etv2(ETS),AGCCGGAAGTGG,63,-,8.211854;ETS1(ETS),GCCGGAAGTG,53,+,10.256266;ETS1(ETS),GCAGGAAGTA,81,+,9.463717;Fli1(ETS),GCAGGAAGTA,90,-,6.576133;Fli1(ETS),GCCGGAAGTG,62,-,7.567547           Etv2(ETS),Etv2(ETS),ETS1(ETS),ETS1(ETS),Fli1(ETS),Fli1(ETS)
Fli1(ETS),AGCGGAAAGG,69,-,5.931610                                                                                                                                                                                               Fli1(ETS)

In [16]:
# Left join motifs to peaks, use V4 in peaks and PositionID in motifs
peaks <- left_join(peaks, motifs, by = c("V4" = "PositionID"))
head(peaks)

# Replace V4 column name with PeakID
colnames(peaks)[colnames(peaks) == "V4"] <- "PeakID"
# Replace V5 with Cluster
colnames(peaks)[colnames(peaks) == "V5"] <- "Cluster"

head(peaks)

  seqnames start    end      width strand V4               V5
1 1         7397451  7398450 1000  *      shRunx3_Runx1_5  cluster_2
2 1         9847901  9848700  800  *      shCd19_Runx1_27  cluster_2
3 1        10037651 10038650 1000  *      shCd19_Runx3_1   cluster_1
4 1        13371951 13373200 1250  *      shCd19_Runx3_2   cluster_2
5 1        13374001 13374750  750  *      shCd19_Runx1_46  cluster_2
6 1        13382101 13382950  850  *      shRunx3_Runx3_33 cluster_2
  annotation                                                    geneChr
1 Promoter (<=1kb)                                              29
2 Promoter (<=1kb)                                              29
3 Promoter (<=1kb)                                              29
4 Promoter (<=1kb)                                              29
5 Promoter (<=1kb)                                              29
6 Intron (ENSMUST00000185813/ENSMUSG00000101476, intron 1 of 1) 29
  geneStart ⋯ geneId             transcriptId       distanceToTSS
1  7349406  ⋯ ENSMUSG00000097797 ENSMUST00000181554    0
2  9848272  ⋯ ENSMUSG00000025915 ENSMUST00000171265    0
3 10024601  ⋯ ENSMUSG00000025917 ENSMUST00000027050    0
4 13139105  ⋯ ENSMUSG00000005886 ENSMUST00000081713    0
5 13139159  ⋯ ENSMUSG00000005886 ENSMUST00000068304    0
6 13376070  ⋯ ENSMUSG00000101476 ENSMUST00000185813 6031
  flank_txIds
1 ENSMUST00000104056;ENSMUST00000181554;ENSMUST00000193106;ENSMUST00000193732;ENSMUST00000193428;ENSMUST00000192649;ENSMUST00000194886;ENSMUST00000193998
2 ENSMUST00000088658;ENSMUST00000115468;ENSMUST00000188212;ENSMUST00000166384;ENSMUST00000188782;ENSMUST00000168907;ENSMUST00000188625;ENSMUST00000188738;ENSMUST00000188298;ENSMUST00000171265;ENSMUST00000188830;ENSMUST00000189050;ENSMUST00000097826;ENSMUST00000191338;ENSMUST00000188486;ENSMUST00000147000;ENSMUST00000124874;ENSMUST00000027049;ENSMUST00000130102;ENSMUST00000176398;ENSMUST00000155163;ENSMUST00000057438;ENSMUST00000052843;ENSMUST00000171802;ENSMUST00000125294;ENSMUST00000140948;ENSMUST00000118098;ENSMUST00000183059;ENSMUST00000063059;ENSMUST00000134692;ENSMUST00000158291;ENSMUST00000175437;ENSMUST00000181821;ENSMUST00000181358;ENSMUST00000191287;ENSMUST00000189431;ENSMUST00000189322;ENSMUST00000182580;ENSMUST00000182819;ENSMUST00000182043;ENSMUST00000182498;ENSMUST00000182742;ENSMUST00000185184;ENSMUST00000097824;ENSMUST00000192299
3 ENSMUST00000166384;ENSMUST00000188782;ENSMUST00000168907;ENSMUST00000188738;ENSMUST00000188298;ENSMUST00000171265;ENSMUST00000097826;ENSMUST00000191338;ENSMUST00000188486;ENSMUST00000147000;ENSMUST00000124874;ENSMUST00000027049;ENSMUST00000130102;ENSMUST00000176398;ENSMUST00000155163;ENSMUST00000027050;ENSMUST00000190155;ENSMUST00000186528;ENSMUST00000188619;ENSMUST00000139578;ENSMUST00000150509;ENSMUST00000191296;ENSMUST00000052843;ENSMUST00000171802;ENSMUST00000125294;ENSMUST00000140948;ENSMUST00000118098;ENSMUST00000183059;ENSMUST00000190610;ENSMUST00000191012;ENSMUST00000071087;ENSMUST00000143606;ENSMUST00000191360;ENSMUST00000117415;ENSMUST00000191521;ENSMUST00000118263;ENSMUST00000122156;ENSMUST00000190063;ENSMUST00000119714;ENSMUST00000134716;ENSMUST00000155974;ENSMUST00000186294;ENSMUST00000149214;ENSMUST00000190318;ENSMUST00000188249;ENSMUST00000153804;ENSMUST00000188449;ENSMUST00000123261;ENSMUST00000185422;ENSMUST00000190625;ENSMUST00000187226;ENSMUST00000136283;ENSMUST00000128164;ENSMUST00000136898;ENSMUST00000148663;ENSMUST00000088615;ENSMUST00000187417;ENSMUST00000142497;ENSMUST00000156563;ENSMUST00000128834;ENSMUST00000131556;ENSMUST00000134692;ENSMUST00000157528;ENSMUST00000175437;ENSMUST00000179194;ENSMUST00000182580;ENSMUST00000182819;ENSMUST00000182043;ENSMUST00000182498;ENSMUST00000182742;ENSMUST00000185184;ENSMUST00000097824;ENSMUST00000194474;ENSMUST00000192299
4 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
5 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
6 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
  flank_geneIds
1 ENSMUSG00000077244;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000102768;ENSMUSG00000103067;ENSMUSG00000103498
2 ENSMUSG00000025912;ENSMUSG00000025912;ENSMUSG00000025912;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000045210;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046334;ENSMUSG00000087199;ENSMUSG00000088916;ENSMUSG00000093178;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000099032;ENSMUSG00000099032;ENSMUSG00000104025
3 ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000087199;ENSMUSG00000088153;ENSMUSG00000093178;ENSMUSG00000095780;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000099032;ENSMUSG00000099032;ENSMUSG00000102356;ENSMUSG00000104025
4 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
5 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
6 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
  flank_gene_distances
1 131648;0;0;0;-16062;82000;-99518;-12229
2 -147692;-147877;-148247;0;0;0;49743;0;0;0;0;0;0;-34767;-46727;136992;154753;160436;160430;160430;160430;-99519;-59938;-59938;-59968;-59970;-62614;-83420;-45348;-133687;-13299;93849;100253;99945;99420;99314;64123;95418;94523;94197;95403;95417;119232;114109;-118614
3 0;0;0;0;0;0;0;154184;142224;-51959;-34198;-28515;-28521;-28521;-28521;0;-2523;0;0;0;0;0;129013;129013;128983;128981;126337;105531;0;0;0;0;0;0;-1117;-1123;-1123;-1127;-1135;-1173;-1505;-7843;-18274;-32533;-35732;-36210;-36263;-49097;-57214;-65578;-74226;-76775;-87334;-91309;-95320;194020;103051;115880;121410;122656;194020;55264;-127889;-95102;-27734;-93533;-94428;-94754;-93548;-93534;-69719;-74842;19294;70337
4 0;0;0;0;0;0;0;-72229;-37342;109753;34455;0;-81445;-15221;-23747;-135517;-73044
5 0;0;0;0;0;0;0;-74279;-39392;111803;32905;0;-83495;-17271;-25797;-137567;-75094
6 0;0;0;0;0;0;0;-82379;-47492;119903;24705;0;-91595;-25371;-33897;-145667;-83194
  geneSymbol
1 Gm26901
2 Sgk3
3 Cops5
4 Ncoa2
5 Ncoa2
6 Gm29570
  flank_geneSymbols
1 Gm23274;Gm26901;Gm26901;Gm26901;Gm26901;Gm19002;Gm30414;Gm18984
2 Mybl1;Mybl1;Mybl1;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Vcpip1;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Gm6195;Gm15818;Gm22607;Snord87;1700034P13Rik;1700034P13Rik;1700034P13Rik;1700034P13Rik;1700034P13Rik;Snhg6;Snhg6;Snhg6;Snhg6;Snhg6;Tcf24;Tcf24;E330040D14Rik
3 Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Cops5;Cops5;Cops5;Cops5;Cops5;Cops5;Cops5;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Gm15818;Gm26348;Snord87;Gm24674;Snhg6;Snhg6;Snhg6;Snhg6;Snhg6;Tcf24;Tcf24;1700047N06Rik;E330040D14Rik
4 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702
5 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702
6 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702
  Motif
1 Etv2(ETS),GGCAGGAAGTCC,-36,-,8.140027;ETS1(ETS),GCAGGAAGTC,-46,+,9.597248;Fli1(ETS),GCAGGAAGTC,-37,-,6.526741
2 ETS:RUNX(ETS,Runt),CACGGATGTGGG,-60,+,8.591579;KLF17(Zf),TGTGGGCGGGAC,-43,-,9.340865;KLF1(Zf),GTGGGCGGGACG,-53,+,8.319507;KLF1(Zf),GCGGGCGGGGCG,-36,+,7.696170
3 Fli1(ETS),GCCGGAAGGC,15,-,6.120476;KLF1(Zf),GAAGGCGGGACT,10,+,7.515942;Stat3(Stat),CTGCCAGGAA,28,+,8.372475;Stat3(Stat),TGCCAGGAAG,38,-,8.155650
4 Etv2(ETS),CTCCTTCCTGCC,-77,+,7.295860;KLF17(Zf),ACCCCGCCTCCT,-84,+,9.870320;KLF1(Zf),AACCCCGCCTCC,-74,-,8.118730
5 RUNX(Runt),CTGTGGTCTA,7,-,9.051514;RUNX-AML(Runt),GCTGTGGTCT,-3,+,9.731169;RUNX2(Runt),GGCTGTGGTCTA,7,-,8.585774;RUNX1(Runt),GCTGTGGTCT,6,-,8.558749
6 Eomes(T-box),TTTCTCACCA,8,+,6.779921;Tbet(T-box),TTTCTCACCA,17,-,6.992082;Tbx21(T-box),TTTCTCACCA,17,-,7.408326
  MotifNames
1 Etv2(ETS),ETS1(ETS),Fli1(ETS)
2 ETS:RUNX(ETS,KLF17(Zf),KLF1(Zf),KLF1(Zf)
3 Fli1(ETS),KLF1(Zf),Stat3(Stat),Stat3(Stat)
4 Etv2(ETS),KLF17(Zf),KLF1(Zf)
5 RUNX(Runt),RUNX-AML(Runt),RUNX2(Runt),RUNX1(Runt)
6 Eomes(T-box),Tbet(T-box),Tbx21(T-box)

  seqnames start    end      width strand PeakID           Cluster
1 1         7397451  7398450 1000  *      shRunx3_Runx1_5  cluster_2
2 1         9847901  9848700  800  *      shCd19_Runx1_27  cluster_2
3 1        10037651 10038650 1000  *      shCd19_Runx3_1   cluster_1
4 1        13371951 13373200 1250  *      shCd19_Runx3_2   cluster_2
5 1        13374001 13374750  750  *      shCd19_Runx1_46  cluster_2
6 1        13382101 13382950  850  *      shRunx3_Runx3_33 cluster_2
  annotation                                                    geneChr
1 Promoter (<=1kb)                                              29
2 Promoter (<=1kb)                                              29
3 Promoter (<=1kb)                                              29
4 Promoter (<=1kb)                                              29
5 Promoter (<=1kb)                                              29
6 Intron (ENSMUST00000185813/ENSMUSG00000101476, intron 1 of 1) 29
  geneStart ⋯ geneId             transcriptId       distanceToTSS
1  7349406  ⋯ ENSMUSG00000097797 ENSMUST00000181554    0
2  9848272  ⋯ ENSMUSG00000025915 ENSMUST00000171265    0
3 10024601  ⋯ ENSMUSG00000025917 ENSMUST00000027050    0
4 13139105  ⋯ ENSMUSG00000005886 ENSMUST00000081713    0
5 13139159  ⋯ ENSMUSG00000005886 ENSMUST00000068304    0
6 13376070  ⋯ ENSMUSG00000101476 ENSMUST00000185813 6031
  flank_txIds
1 ENSMUST00000104056;ENSMUST00000181554;ENSMUST00000193106;ENSMUST00000193732;ENSMUST00000193428;ENSMUST00000192649;ENSMUST00000194886;ENSMUST00000193998
2 ENSMUST00000088658;ENSMUST00000115468;ENSMUST00000188212;ENSMUST00000166384;ENSMUST00000188782;ENSMUST00000168907;ENSMUST00000188625;ENSMUST00000188738;ENSMUST00000188298;ENSMUST00000171265;ENSMUST00000188830;ENSMUST00000189050;ENSMUST00000097826;ENSMUST00000191338;ENSMUST00000188486;ENSMUST00000147000;ENSMUST00000124874;ENSMUST00000027049;ENSMUST00000130102;ENSMUST00000176398;ENSMUST00000155163;ENSMUST00000057438;ENSMUST00000052843;ENSMUST00000171802;ENSMUST00000125294;ENSMUST00000140948;ENSMUST00000118098;ENSMUST00000183059;ENSMUST00000063059;ENSMUST00000134692;ENSMUST00000158291;ENSMUST00000175437;ENSMUST00000181821;ENSMUST00000181358;ENSMUST00000191287;ENSMUST00000189431;ENSMUST00000189322;ENSMUST00000182580;ENSMUST00000182819;ENSMUST00000182043;ENSMUST00000182498;ENSMUST00000182742;ENSMUST00000185184;ENSMUST00000097824;ENSMUST00000192299
3 ENSMUST00000166384;ENSMUST00000188782;ENSMUST00000168907;ENSMUST00000188738;ENSMUST00000188298;ENSMUST00000171265;ENSMUST00000097826;ENSMUST00000191338;ENSMUST00000188486;ENSMUST00000147000;ENSMUST00000124874;ENSMUST00000027049;ENSMUST00000130102;ENSMUST00000176398;ENSMUST00000155163;ENSMUST00000027050;ENSMUST00000190155;ENSMUST00000186528;ENSMUST00000188619;ENSMUST00000139578;ENSMUST00000150509;ENSMUST00000191296;ENSMUST00000052843;ENSMUST00000171802;ENSMUST00000125294;ENSMUST00000140948;ENSMUST00000118098;ENSMUST00000183059;ENSMUST00000190610;ENSMUST00000191012;ENSMUST00000071087;ENSMUST00000143606;ENSMUST00000191360;ENSMUST00000117415;ENSMUST00000191521;ENSMUST00000118263;ENSMUST00000122156;ENSMUST00000190063;ENSMUST00000119714;ENSMUST00000134716;ENSMUST00000155974;ENSMUST00000186294;ENSMUST00000149214;ENSMUST00000190318;ENSMUST00000188249;ENSMUST00000153804;ENSMUST00000188449;ENSMUST00000123261;ENSMUST00000185422;ENSMUST00000190625;ENSMUST00000187226;ENSMUST00000136283;ENSMUST00000128164;ENSMUST00000136898;ENSMUST00000148663;ENSMUST00000088615;ENSMUST00000187417;ENSMUST00000142497;ENSMUST00000156563;ENSMUST00000128834;ENSMUST00000131556;ENSMUST00000134692;ENSMUST00000157528;ENSMUST00000175437;ENSMUST00000179194;ENSMUST00000182580;ENSMUST00000182819;ENSMUST00000182043;ENSMUST00000182498;ENSMUST00000182742;ENSMUST00000185184;ENSMUST00000097824;ENSMUST00000194474;ENSMUST00000192299
4 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
5 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
6 ENSMUST00000081713;ENSMUST00000068304;ENSMUST00000006037;ENSMUST00000147927;ENSMUST00000143603;ENSMUST00000139970;ENSMUST00000124088;ENSMUST00000145280;ENSMUST00000157157;ENSMUST00000183805;ENSMUST00000187246;ENSMUST00000185813;ENSMUST00000194484;ENSMUST00000195718;ENSMUST00000195506;ENSMUST00000195811;ENSMUST00000194357
  flank_geneIds
1 ENSMUSG00000077244;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000097797;ENSMUSG00000102768;ENSMUSG00000103067;ENSMUSG00000103498
2 ENSMUSG00000025912;ENSMUSG00000025912;ENSMUSG00000025912;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000045210;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046334;ENSMUSG00000087199;ENSMUSG00000088916;ENSMUSG00000093178;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000097893;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000099032;ENSMUSG00000099032;ENSMUSG00000104025
3 ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025915;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025916;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000025917;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000046101;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000056763;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000067851;ENSMUSG00000087199;ENSMUSG00000088153;ENSMUSG00000093178;ENSMUSG00000095780;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000098234;ENSMUSG00000099032;ENSMUSG00000099032;ENSMUSG00000102356;ENSMUSG00000104025
4 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
5 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
6 ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000005886;ENSMUSG00000087782;ENSMUSG00000099183;ENSMUSG00000101171;ENSMUSG00000101476;ENSMUSG00000102639;ENSMUSG00000102664;ENSMUSG00000103085;ENSMUSG00000103495;ENSMUSG00000104170
  flank_gene_distances
1 131648;0;0;0;-16062;82000;-99518;-12229
2 -147692;-147877;-148247;0;0;0;49743;0;0;0;0;0;0;-34767;-46727;136992;154753;160436;160430;160430;160430;-99519;-59938;-59938;-59968;-59970;-62614;-83420;-45348;-133687;-13299;93849;100253;99945;99420;99314;64123;95418;94523;94197;95403;95417;119232;114109;-118614
3 0;0;0;0;0;0;0;154184;142224;-51959;-34198;-28515;-28521;-28521;-28521;0;-2523;0;0;0;0;0;129013;129013;128983;128981;126337;105531;0;0;0;0;0;0;-1117;-1123;-1123;-1127;-1135;-1173;-1505;-7843;-18274;-32533;-35732;-36210;-36263;-49097;-57214;-65578;-74226;-76775;-87334;-91309;-95320;194020;103051;115880;121410;122656;194020;55264;-127889;-95102;-27734;-93533;-94428;-94754;-93548;-93534;-69719;-74842;19294;70337
4 0;0;0;0;0;0;0;-72229;-37342;109753;34455;0;-81445;-15221;-23747;-135517;-73044
5 0;0;0;0;0;0;0;-74279;-39392;111803;32905;0;-83495;-17271;-25797;-137567;-75094
6 0;0;0;0;0;0;0;-82379;-47492;119903;24705;0;-91595;-25371;-33897;-145667;-83194
  geneSymbol
1 Gm26901
2 Sgk3
3 Cops5
4 Ncoa2
5 Ncoa2
6 Gm29570
  flank_geneSymbols
1 Gm23274;Gm26901;Gm26901;Gm26901;Gm26901;Gm19002;Gm30414;Gm18984
2 Mybl1;Mybl1;Mybl1;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Vcpip1;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Gm6195;Gm15818;Gm22607;Snord87;1700034P13Rik;1700034P13Rik;1700034P13Rik;1700034P13Rik;1700034P13Rik;Snhg6;Snhg6;Snhg6;Snhg6;Snhg6;Tcf24;Tcf24;E330040D14Rik
3 Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Sgk3;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Ppp1r42;Cops5;Cops5;Cops5;Cops5;Cops5;Cops5;Cops5;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Mcmdc2;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Cspp1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Arfgef1;Gm15818;Gm26348;Snord87;Gm24674;Snhg6;Snhg6;Snhg6;Snhg6;Snhg6;Tcf24;Tcf24;1700047N06Rik;E330040D14Rik
4 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702
5 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702
6 Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Ncoa2;Gm23169;Gm27881;Gm7593;Gm29570;Gm38223;Gm38380;Gm38120;Gm37409;Gm37702
  Motif
1 Etv2(ETS),GGCAGGAAGTCC,-36,-,8.140027;ETS1(ETS),GCAGGAAGTC,-46,+,9.597248;Fli1(ETS),GCAGGAAGTC,-37,-,6.526741
2 ETS:RUNX(ETS,Runt),CACGGATGTGGG,-60,+,8.591579;KLF17(Zf),TGTGGGCGGGAC,-43,-,9.340865;KLF1(Zf),GTGGGCGGGACG,-53,+,8.319507;KLF1(Zf),GCGGGCGGGGCG,-36,+,7.696170
3 Fli1(ETS),GCCGGAAGGC,15,-,6.120476;KLF1(Zf),GAAGGCGGGACT,10,+,7.515942;Stat3(Stat),CTGCCAGGAA,28,+,8.372475;Stat3(Stat),TGCCAGGAAG,38,-,8.155650
4 Etv2(ETS),CTCCTTCCTGCC,-77,+,7.295860;KLF17(Zf),ACCCCGCCTCCT,-84,+,9.870320;KLF1(Zf),AACCCCGCCTCC,-74,-,8.118730
5 RUNX(Runt),CTGTGGTCTA,7,-,9.051514;RUNX-AML(Runt),GCTGTGGTCT,-3,+,9.731169;RUNX2(Runt),GGCTGTGGTCTA,7,-,8.585774;RUNX1(Runt),GCTGTGGTCT,6,-,8.558749
6 Eomes(T-box),TTTCTCACCA,8,+,6.779921;Tbet(T-box),TTTCTCACCA,17,-,6.992082;Tbx21(T-box),TTTCTCACCA,17,-,7.408326
  MotifNames
1 Etv2(ETS),ETS1(ETS),Fli1(ETS)
2 ETS:RUNX(ETS,KLF17(Zf),KLF1(Zf),KLF1(Zf)
3 Fli1(ETS),KLF1(Zf),Stat3(Stat),Stat3(Stat)
4 Etv2(ETS),KLF17(Zf),KLF1(Zf)
5 RUNX(Runt),RUNX-AML(Runt),RUNX2(Runt),RUNX1(Runt)
6 Eomes(T-box),Tbet(T-box),Tbx21(T-box)

In [18]:
# Save CSV and RDS
write.csv(peaks, "04_peakAnnotation/peaks.annotated.csv", row.names = FALSE)
saveRDS(peaks, "04_peakAnnotation/peaks.annotated.rds")