# 04 Peak Annotation

## Initialize

In [1]:
# Load Libraries
library(ChIPseeker)
library(GenomicFeatures)
library(dplyr)
library(tidyr)

# Move to working directory
setwd("/home/dalbao/AlbaoRunx3Manuscript/cutnrun")

# Make folder if it does not exist
if (!dir.exists("04_peakAnnotation")) {
    dir.create("04_peakAnnotation", recursive = TRUE)
}

ChIPseeker v1.42.0 Learn more at https://yulab-smu.top/contribution-knowledge-mining/

Please cite:

Guangchuang Yu, Li-Gen Wang, and Qing-Yu He. ChIPseeker: an
R/Bioconductor package for ChIP peak annotation, comparison and
visualization. Bioinformatics. 2015, 31(14):2382-2383

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, saveRDS, setdiff,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: GenomicRanges

Loading required package: AnnotationDbi

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘dplyr’


The following object is masked from ‘package:AnnotationDbi’:

    select


The following object is masked from ‘package:Biobase’:

    combine


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘tidyr’


The following object is masked from ‘package:S4Vectors’:

    expand

## Import GTF Data

In [2]:
# Create a TxDb object for annotations 
txdb <- makeTxDbFromGFF("source_data/genes.gtf", format = "gtf") # GRCm38

Warning message in call_fun_in_txdbmaker("makeTxDbFromGFF", ...):
“makeTxDbFromGFF() has moved to the txdbmaker package. Please call
  txdbmaker::makeTxDbFromGFF() to get rid of this warning.”
Import genomic features from the file as a GRanges object ...
OK

Prepare the 'metadata' data frame ...
OK

Make the TxDb object ...
Warning message in .get_cds_IDX(mcols0$type, mcols0$phase):
“The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.”
OK

## Annotate Peaks with Flanks

In [3]:
# Annotate peaks
cluster1 <- annotatePeak(
    peak = "01_peakEDA/splitTruePeaks.good/cluster_1.bed",
    tssRegion = c(-3000, 3000),     # Region to consider as TSS proximal
    TxDb = txdb,                    # Ensembl TxDb for GRCm38
    addFlankGeneInfo = TRUE,        # Add gene information
    flankDistance = 150000          # Distance to consider as gene body
)
cluster2 <- annotatePeak(
    peak = "01_peakEDA/splitTruePeaks.good/cluster_2.bed",
    tssRegion = c(-3000, 3000),     # Region to consider as TSS proximal
    TxDb = txdb,                    # Ensembl TxDb for GRCm38
    addFlankGeneInfo = TRUE,        # Add gene information
    flankDistance = 150000          # Distance to consider as gene body
)

>> loading peak file...				 2026-07-21 05:58:14
>> preparing features information...		 2026-07-21 05:58:14
>> identifying nearest features...		 2026-07-21 05:58:14
>> calculating distance from peak to TSS...	 2026-07-21 05:58:14
>> assigning genomic annotation...		 2026-07-21 05:58:14
>> adding flank feature information from peaks...	 2026-07-21 05:58:24
>> assigning chromosome lengths			 2026-07-21 05:58:25
>> done...					 2026-07-21 05:58:25
>> loading peak file...				 2026-07-21 05:58:25
>> preparing features information...		 2026-07-21 05:58:25
>> identifying nearest features...		 2026-07-21 05:58:25
>> calculating distance from peak to TSS...	 2026-07-21 05:58:25
>> assigning genomic annotation...		 2026-07-21 05:58:25
>> adding flank feature information from peaks...	 2026-07-21 05:58:26
>> assigning chromosome lengths			 2026-07-21 05:58:28
>> done...					 2026-07-21 05:58:28

In [4]:
cluster1

Annotated peaks generated by ChIPseeker
2789/2789  peaks were annotated
Genomic Annotation Summary:
              Feature   Frequency
8    Promoter (<=1kb) 52.99390463
9    Promoter (1-2kb)  4.69702402
10   Promoter (2-3kb)  3.04768734
3              5' UTR  0.10756544
2              3' UTR  1.21907494
6          Other Exon  0.89637863
1          1st Intron  7.88813195
7        Other Intron 10.21871639
5  Downstream (<=300)  0.07171029
4   Distal Intergenic 18.85980638

In [5]:
cluster2

Annotated peaks generated by ChIPseeker
6019/6019  peaks were annotated
Genomic Annotation Summary:
              Feature   Frequency
9    Promoter (<=1kb) 53.28127596
10   Promoter (1-2kb)  3.75477654
11   Promoter (2-3kb)  2.94068782
4              5' UTR  0.14952650
3              3' UTR  1.07991361
1            1st Exon  0.04984217
7          Other Exon  1.74447583
2          1st Intron  7.12742981
8        Other Intron 10.68283768
6  Downstream (<=300)  0.09968433
5   Distal Intergenic 19.08954976

In [6]:
cluster1_df <- as.data.frame(cluster1)
head(cluster1_df)
cluster2_df <- as.data.frame(cluster2)
head(cluster2_df)

  seqnames start    end      width strand V4         V5       V6 V7
1 14       54223651 54224100  450  *      924.779_r5  3.32921 .  54223650
2 1        64531551 64533300 1750  *      7739.42    13.46730 .  64531550
3 12       98269451 98270700 1250  *      13697.4    24.54790 .  98269450
4 12       98269701 98270550  850  *      2395.18     4.25398 .  98269700
5 12       98269801 98270500  700  *      2242.74     5.49241 .  98269800
6 12       98269751 98270700  950  *      4517.37     7.85629 .  98269750
  V8       ⋯ geneStart geneEnd  geneLength geneStrand geneId
1 54224100 ⋯ 54220521  54224206  3686      1          ENSMUSG00000076928
2 64533300 ⋯ 64532645  64597695 65051      1          ENSMUSG00000025958
3 98270700 ⋯ 98268635  98276624  7990      1          ENSMUSG00000021886
4 98270550 ⋯ 98268635  98276624  7990      1          ENSMUSG00000021886
5 98270500 ⋯ 98268635  98276624  7990      1          ENSMUSG00000021886
6 98270700 ⋯ 98268635  98276624  7990      1          ENSMUSG00000021886
  transcriptId       distanceToTSS
1 ENSMUST00000198398 3130
2 ENSMUST00000185594    0
3 ENSMUST00000075072  816
4 ENSMUST00000075072 1066
5 ENSMUST00000075072 1166
6 ENSMUST00000075072 1116
  flank_txIds
1 ENSMUST00000000984;ENSMUST00000197440;ENSMUST00000195970;ENSMUST00000196966;ENSMUST00000198107;ENSMUST00000000985;ENSMUST00000196882;ENSMUST00000022781;ENSMUST00000128231;ENSMUST00000180359;ENSMUST00000199338;ENSMUST00000041197;ENSMUST00000197802;ENSMUST00000196699;ENSMUST00000197605;ENSMUST00000199068;ENSMUST00000197807;ENSMUST00000059996;ENSMUST00000103679;ENSMUST00000103682;ENSMUST00000103683;ENSMUST00000103685;ENSMUST00000197589;ENSMUST00000103686;ENSMUST00000103687;ENSMUST00000103688;ENSMUST00000196977;ENSMUST00000103689;ENSMUST00000103690;ENSMUST00000103691;ENSMUST00000103692;ENSMUST00000103693;ENSMUST00000103694;ENSMUST00000199452;ENSMUST00000200046;ENSMUST00000103695;ENSMUST00000103696;ENSMUST00000103697;ENSMUST00000103698;ENSMUST00000103699;ENSMUST00000103700;ENSMUST00000103701;ENSMUST00000103702;ENSMUST00000103703;ENSMUST00000103704;ENSMUST00000103705;ENSMUST00000103706;ENSMUST00000103707;ENSMUST00000103708;ENSMUST00000103709;ENSMUST00000103710;ENSMUST00000103711;ENSMUST00000103712;ENSMUST00000103713;ENSMUST00000103714;ENSMUST00000103715;ENSMUST00000103716;ENSMUST00000103717;ENSMUST00000103718;ENSMUST00000103719;ENSMUST00000103720;ENSMUST00000103721;ENSMUST00000103722;ENSMUST00000103723;ENSMUST00000103724;ENSMUST00000103725;ENSMUST00000103726;ENSMUST00000103727;ENSMUST00000103728;ENSMUST00000103729;ENSMUST00000103730;ENSMUST00000103731;ENSMUST00000103732;ENSMUST00000103733;ENSMUST00000103734;ENSMUST00000103735;ENSMUST00000103736;ENSMUST00000103737;ENSMUST00000103738;ENSMUST00000103739;ENSMUST00000103740;ENSMUST00000198398;ENSMUST00000158844;ENSMUST00000167829;ENSMUST00000165025;ENSMUST00000167781;ENSMUST00000170585;ENSMUST00000165071;ENSMUST00000177564;ENSMUST00000196221;ENSMUST00000179664;ENSMUST00000198124;ENSMUST00000197620;ENSMUST00000196323;ENSMUST00000197949;ENSMUST00000196803;ENSMUST00000200008;ENSMUST00000196637;ENSMUST00000199958;ENSMUST00000196615
2 ENSMUST00000114079;ENSMUST00000053469;ENSMUST00000162806;ENSMUST00000161264;ENSMUST00000185594;ENSMUST00000171164;ENSMUST00000188855;ENSMUST00000187811;ENSMUST00000049932;ENSMUST00000087366;ENSMUST00000186335;ENSMUST00000190876;ENSMUST00000190348;ENSMUST00000187035;ENSMUST00000190979;ENSMUST00000150749;ENSMUST00000175487;ENSMUST00000187877;ENSMUST00000189284;ENSMUST00000186895
3 ENSMUST00000021390;ENSMUST00000075072
4 ENSMUST00000021390;ENSMUST00000075072
5 ENSMUST00000021390;ENSMUST00000075072
6 ENSMUST00000021390;ENSMUST00000075072
  flank_geneIds
1 ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000022174;ENSMUSG00000022174;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000048153;ENSMUSG00000076867;ENSMUSG00000076870;ENSMUSG00000076871;ENSMUSG00000076873;ENSMUSG00000076874;ENSMUSG00000076874;ENSMUSG00000076875;ENSMUSG00000076876;ENSMUSG00000076876;ENSMUSG00000076877;ENSMUSG00000076878;ENSMUSG00000076879;ENSMUSG00000076880;ENSMUSG00000076881;ENSMUSG00000076882;ENSMUSG00000076882;ENSMUSG00000076883;ENSMUSG00000076883;ENSMUSG00000076884;ENSMUSG00000076885;ENSMUSG00000076886;ENSMUSG00000076887;ENSMUSG00000076888;ENSMUSG00000076889;ENSMUSG00000076890;ENSMUSG00000076891;ENSMUSG00000076892;ENSMUSG00000076893;ENSMUSG00000076894;ENSMUSG00000076895;ENSMUSG00000076896;ENSMUSG00000076897;ENSMUSG00000076898;ENSMUSG00000076899;ENSMUSG00000076900;ENSMUSG00000076901;ENSMUSG00000076902;ENSMUSG00000076903;ENSMUSG00000076904;ENSMUSG00000076905;ENSMUSG00000076906;ENSMUSG00000076907;ENSMUSG00000076908;ENSMUSG00000076909;ENSMUSG00000076910;ENSMUSG00000076911;ENSMUSG00000076912;ENSMUSG00000076913;ENSMUSG00000076914;ENSMUSG00000076915;ENSMUSG00000076916;ENSMUSG00000076917;ENSMUSG00000076918;ENSMUSG00000076919;ENSMUSG00000076920;ENSMUSG00000076921;ENSMUSG00000076922;ENSMUSG00000076923;ENSMUSG00000076924;ENSMUSG00000076925;ENSMUSG00000076926;ENSMUSG00000076927;ENSMUSG00000076928;ENSMUSG00000076928;ENSMUSG00000089469;ENSMUSG00000090494;ENSMUSG00000090574;ENSMUSG00000090782;ENSMUSG00000091005;ENSMUSG00000091326;ENSMUSG00000096176;ENSMUSG00000096749;ENSMUSG00000096749;ENSMUSG00000104658;ENSMUSG00000104658;ENSMUSG00000104876;ENSMUSG00000105216;ENSMUSG00000105294;ENSMUSG00000105501;ENSMUSG00000105667;ENSMUSG00000105703;ENSMUSG00000106112
2 ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000087213;ENSMUSG00000093228;ENSMUSG00000099658;ENSMUSG00000100437;ENSMUSG00000101832
3 ENSMUSG00000021003;ENSMUSG00000021886
4 ENSMUSG00000021003;ENSMUSG00000021886
5 ENSMUSG00000021003;ENSMUSG00000021886
6 ENSMUSG00000021003;ENSMUSG00000021886
  flank_gene_distances
1 185360;193599;186116;160067;-136741;-136741;-136945;30004;29814;-30088;-30114;-35132;-35173;-35179;-35207;-38876;-39181;58825;148746;100513;86872;-74357;67518;67518;66371;65146;65144;64388;61007;58335;57412;56061;54965;54965;53843;53842;51315;50823;49961;48909;47878;47380;45730;43689;43077;42133;39877;38952;38293;37550;35756;33785;32705;31990;31348;29161;28836;28013;27570;26403;24861;24210;23265;22874;21876;20517;19229;18540;17910;17098;16512;14258;13733;12181;10963;9874;7360;6359;5815;4837;0;0;106597;41249;68646;67718;62212;61661;101425;110183;110183;-98309;-98256;80800;51851;100223;127536;-110117;73243;-77364
2 83942;83868;82331;83884;0;0;0;0;0;0;0;0;0;-27625;-43088;157359;135217;-76974;-116635;-84484
3 -9992;0
4 -10242;0
5 -10342;0
6 -10292;0

  seqnames start     end       width strand V4         V5       V6 V7
1 4         32248251  32251550 3300  *      10236.8    18.07000 .   32248250
2 14        54222301  54225900 3600  *      4687.82     4.08347 .   54222300
3 1         64530801  64532500 1700  *      1217.57     1.51016 .   64530800
4 1        171627651 171629900 2250  *      3800.49     6.48144 .  171627650
5 12        98271051  98271550  500  *      628.849     1.66460 .   98271050
6 14        54224201  54224600  400  *      786.063_r5  2.40443 .   54224200
  V8        ⋯ geneStart geneEnd   geneLength geneStrand geneId
1  32251550 ⋯  32251761  32265835 14075      1          ENSMUSG00000087049
2  54225900 ⋯  54220521  54224206  3686      1          ENSMUSG00000076928
3  64532500 ⋯  64532645  64597695 65051      1          ENSMUSG00000025958
4 171629900 ⋯ 171634879 171636022  1144      1          ENSMUSG00000103219
5  98271550 ⋯  98268635  98276624  7990      1          ENSMUSG00000021886
6  54224600 ⋯  54220521  54224206  3686      1          ENSMUSG00000076928
  transcriptId       distanceToTSS
1 ENSMUST00000133451  -211
2 ENSMUST00000198398  1780
3 ENSMUST00000185594  -145
4 ENSMUST00000192524 -4979
5 ENSMUST00000075072  2416
6 ENSMUST00000198398  3680
  flank_txIds
1 ENSMUST00000108180;ENSMUST00000037416;ENSMUST00000149201;ENSMUST00000156430;ENSMUST00000118175;ENSMUST00000119323;ENSMUST00000133451
2 ENSMUST00000000984;ENSMUST00000197440;ENSMUST00000195970;ENSMUST00000196966;ENSMUST00000197667;ENSMUST00000198107;ENSMUST00000000985;ENSMUST00000196882;ENSMUST00000022781;ENSMUST00000128231;ENSMUST00000180359;ENSMUST00000199338;ENSMUST00000041197;ENSMUST00000197802;ENSMUST00000196699;ENSMUST00000197605;ENSMUST00000199068;ENSMUST00000197807;ENSMUST00000059996;ENSMUST00000103679;ENSMUST00000103682;ENSMUST00000103683;ENSMUST00000103685;ENSMUST00000197589;ENSMUST00000103686;ENSMUST00000103687;ENSMUST00000103688;ENSMUST00000196977;ENSMUST00000103689;ENSMUST00000103690;ENSMUST00000103691;ENSMUST00000103692;ENSMUST00000103693;ENSMUST00000103694;ENSMUST00000199452;ENSMUST00000200046;ENSMUST00000103695;ENSMUST00000103696;ENSMUST00000103697;ENSMUST00000103698;ENSMUST00000103699;ENSMUST00000103700;ENSMUST00000103701;ENSMUST00000103702;ENSMUST00000103703;ENSMUST00000103704;ENSMUST00000103705;ENSMUST00000103706;ENSMUST00000103707;ENSMUST00000103708;ENSMUST00000103709;ENSMUST00000103710;ENSMUST00000103711;ENSMUST00000103712;ENSMUST00000103713;ENSMUST00000103714;ENSMUST00000103715;ENSMUST00000103716;ENSMUST00000103717;ENSMUST00000103718;ENSMUST00000103719;ENSMUST00000103720;ENSMUST00000103721;ENSMUST00000103722;ENSMUST00000103723;ENSMUST00000103724;ENSMUST00000103725;ENSMUST00000103726;ENSMUST00000103727;ENSMUST00000103728;ENSMUST00000103729;ENSMUST00000103730;ENSMUST00000103731;ENSMUST00000103732;ENSMUST00000103733;ENSMUST00000103734;ENSMUST00000103735;ENSMUST00000103736;ENSMUST00000103737;ENSMUST00000103738;ENSMUST00000103739;ENSMUST00000103740;ENSMUST00000198398;ENSMUST00000158844;ENSMUST00000167829;ENSMUST00000165025;ENSMUST00000167781;ENSMUST00000170585;ENSMUST00000165071;ENSMUST00000177564;ENSMUST00000196221;ENSMUST00000179664;ENSMUST00000198124;ENSMUST00000197620;ENSMUST00000196323;ENSMUST00000197949;ENSMUST00000196803;ENSMUST00000200008;ENSMUST00000196637;ENSMUST00000199958;ENSMUST00000196615
3 ENSMUST00000114079;ENSMUST00000053469;ENSMUST00000162806;ENSMUST00000161264;ENSMUST00000185594;ENSMUST00000171164;ENSMUST00000188855;ENSMUST00000187811;ENSMUST00000049932;ENSMUST00000087366;ENSMUST00000186335;ENSMUST00000190876;ENSMUST00000190348;ENSMUST00000187035;ENSMUST00000190979;ENSMUST00000150749;ENSMUST00000175487;ENSMUST00000187877;ENSMUST00000189284;ENSMUST00000186895
4 ENSMUST00000068878;ENSMUST00000004827;ENSMUST00000143463;ENSMUST00000111277;ENSMUST00000146596;ENSMUST00000004829;ENSMUST00000194797;ENSMUST00000194170;ENSMUST00000195804;ENSMUST00000015460;ENSMUST00000163992;ENSMUST00000015499;ENSMUST00000068584;ENSMUST00000192195;ENSMUST00000192024;ENSMUST00000111276;ENSMUST00000194531;ENSMUST00000194791;ENSMUST00000043094;ENSMUST00000168184;ENSMUST00000043170;ENSMUST00000118448;ENSMUST00000081527;ENSMUST00000157666;ENSMUST00000181170;ENSMUST00000165827;ENSMUST00000083099;ENSMUST00000082776;ENSMUST00000183842;ENSMUST00000194468;ENSMUST00000194143;ENSMUST00000194280;ENSMUST00000192524;ENSMUST00000194539;ENSMUST00000195218;ENSMUST00000194562;ENSMUST00000194947
5 ENSMUST00000021390;ENSMUST00000075072
6 ENSMUST00000000984;ENSMUST00000197440;ENSMUST00000195970;ENSMUST00000196966;ENSMUST00000197667;ENSMUST00000198107;ENSMUST00000000985;ENSMUST00000196882;ENSMUST00000022781;ENSMUST00000128231;ENSMUST00000180359;ENSMUST00000199338;ENSMUST00000041197;ENSMUST00000197802;ENSMUST00000196699;ENSMUST00000197605;ENSMUST00000199068;ENSMUST00000197807;ENSMUST00000059996;ENSMUST00000103679;ENSMUST00000103682;ENSMUST00000103683;ENSMUST00000103685;ENSMUST00000197589;ENSMUST00000103686;ENSMUST00000103687;ENSMUST00000103688;ENSMUST00000196977;ENSMUST00000103689;ENSMUST00000103690;ENSMUST00000103691;ENSMUST00000103692;ENSMUST00000103693;ENSMUST00000103694;ENSMUST00000199452;ENSMUST00000200046;ENSMUST00000103695;ENSMUST00000103696;ENSMUST00000103697;ENSMUST00000103698;ENSMUST00000103699;ENSMUST00000103700;ENSMUST00000103701;ENSMUST00000103702;ENSMUST00000103703;ENSMUST00000103704;ENSMUST00000103705;ENSMUST00000103706;ENSMUST00000103707;ENSMUST00000103708;ENSMUST00000103709;ENSMUST00000103710;ENSMUST00000103711;ENSMUST00000103712;ENSMUST00000103713;ENSMUST00000103714;ENSMUST00000103715;ENSMUST00000103716;ENSMUST00000103717;ENSMUST00000103718;ENSMUST00000103719;ENSMUST00000103720;ENSMUST00000103721;ENSMUST00000103722;ENSMUST00000103723;ENSMUST00000103724;ENSMUST00000103725;ENSMUST00000103726;ENSMUST00000103727;ENSMUST00000103728;ENSMUST00000103729;ENSMUST00000103730;ENSMUST00000103731;ENSMUST00000103732;ENSMUST00000103733;ENSMUST00000103734;ENSMUST00000103735;ENSMUST00000103736;ENSMUST00000103737;ENSMUST00000103738;ENSMUST00000103739;ENSMUST00000103740;ENSMUST00000198398;ENSMUST00000158844;ENSMUST00000167829;ENSMUST00000165025;ENSMUST00000167781;ENSMUST00000170585;ENSMUST00000165071;ENSMUST00000177564;ENSMUST00000196221;ENSMUST00000179664;ENSMUST00000198124;ENSMUST00000197620;ENSMUST00000196323;ENSMUST00000197949;ENSMUST00000196803;ENSMUST00000200008;ENSMUST00000196637;ENSMUST00000199958;ENSMUST00000196615
  flank_geneIds
1 ENSMUSG00000040270;ENSMUSG00000040270;ENSMUSG00000040270;ENSMUSG00000040270;ENSMUSG00000083564;ENSMUSG00000083872;ENSMUSG00000087049
2 ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000022174;ENSMUSG00000022174;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000048153;ENSMUSG00000076867;ENSMUSG00000076870;ENSMUSG00000076871;ENSMUSG00000076873;ENSMUSG00000076874;ENSMUSG00000076874;ENSMUSG00000076875;ENSMUSG00000076876;ENSMUSG00000076876;ENSMUSG00000076877;ENSMUSG00000076878;ENSMUSG00000076879;ENSMUSG00000076880;ENSMUSG00000076881;ENSMUSG00000076882;ENSMUSG00000076882;ENSMUSG00000076883;ENSMUSG00000076883;ENSMUSG00000076884;ENSMUSG00000076885;ENSMUSG00000076886;ENSMUSG00000076887;ENSMUSG00000076888;ENSMUSG00000076889;ENSMUSG00000076890;ENSMUSG00000076891;ENSMUSG00000076892;ENSMUSG00000076893;ENSMUSG00000076894;ENSMUSG00000076895;ENSMUSG00000076896;ENSMUSG00000076897;ENSMUSG00000076898;ENSMUSG00000076899;ENSMUSG00000076900;ENSMUSG00000076901;ENSMUSG00000076902;ENSMUSG00000076903;ENSMUSG00000076904;ENSMUSG00000076905;ENSMUSG00000076906;ENSMUSG00000076907;ENSMUSG00000076908;ENSMUSG00000076909;ENSMUSG00000076910;ENSMUSG00000076911;ENSMUSG00000076912;ENSMUSG00000076913;ENSMUSG00000076914;ENSMUSG00000076915;ENSMUSG00000076916;ENSMUSG00000076917;ENSMUSG00000076918;ENSMUSG00000076919;ENSMUSG00000076920;ENSMUSG00000076921;ENSMUSG00000076922;ENSMUSG00000076923;ENSMUSG00000076924;ENSMUSG00000076925;ENSMUSG00000076926;ENSMUSG00000076927;ENSMUSG00000076928;ENSMUSG00000076928;ENSMUSG00000089469;ENSMUSG00000090494;ENSMUSG00000090574;ENSMUSG00000090782;ENSMUSG00000091005;ENSMUSG00000091326;ENSMUSG00000096176;ENSMUSG00000096749;ENSMUSG00000096749;ENSMUSG00000104658;ENSMUSG00000104658;ENSMUSG00000104876;ENSMUSG00000105216;ENSMUSG00000105294;ENSMUSG00000105501;ENSMUSG00000105667;ENSMUSG00000105703;ENSMUSG00000106112
3 ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000087213;ENSMUSG00000093228;ENSMUSG00000099658;ENSMUSG00000100437;ENSMUSG00000101832
4 ENSMUSG00000004707;ENSMUSG00000004707;ENSMUSG00000004707;ENSMUSG00000004707;ENSMUSG00000004707;ENSMUSG00000004709;ENSMUSG00000004709;ENSMUSG00000004709;ENSMUSG00000004709;ENSMUSG00000015316;ENSMUSG00000015316;ENSMUSG00000015355;ENSMUSG00000015355;ENSMUSG00000038179;ENSMUSG00000038179;ENSMUSG00000038179;ENSMUSG00000038179;ENSMUSG00000038179;ENSMUSG00000038209;ENSMUSG00000038209;ENSMUSG00000038218;ENSMUSG00000059058;ENSMUSG00000060244;ENSMUSG00000088291;ENSMUSG00000091993;ENSMUSG00000091993;ENSMUSG00000094668;ENSMUSG00000095636;ENSMUSG00000098316;ENSMUSG00000103083;ENSMUSG00000103083;ENSMUSG00000103137;ENSMUSG00000103219;ENSMUSG00000103883;ENSMUSG00000103980;ENSMUSG00000104224;ENSMUSG00000104440
5 ENSMUSG00000021003;ENSMUSG00000021886
6 ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000022174;ENSMUSG00000022174;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000048153;ENSMUSG00000076867;ENSMUSG00000076870;ENSMUSG00000076871;ENSMUSG00000076873;ENSMUSG00000076874;ENSMUSG00000076874;ENSMUSG00000076875;ENSMUSG00000076876;ENSMUSG00000076876;ENSMUSG00000076877;ENSMUSG00000076878;ENSMUSG00000076879;ENSMUSG00000076880;ENSMUSG00000076881;ENSMUSG00000076882;ENSMUSG00000076882;ENSMUSG00000076883;ENSMUSG00000076883;ENSMUSG00000076884;ENSMUSG00000076885;ENSMUSG00000076886;ENSMUSG00000076887;ENSMUSG00000076888;ENSMUSG00000076889;ENSMUSG00000076890;ENSMUSG00000076891;ENSMUSG00000076892;ENSMUSG00000076893;ENSMUSG00000076894;ENSMUSG00000076895;ENSMUSG00000076896;ENSMUSG00000076897;ENSMUSG00000076898;ENSMUSG00000076899;ENSMUSG00000076900;ENSMUSG00000076901;ENSMUSG00000076902;ENSMUSG00000076903;ENSMUSG00000076904;ENSMUSG00000076905;ENSMUSG00000076906;ENSMUSG00000076907;ENSMUSG00000076908;ENSMUSG00000076909;ENSMUSG00000076910;ENSMUSG00000076911;ENSMUSG00000076912;ENSMUSG00000076913;ENSMUSG00000076914;ENSMUSG00000076915;ENSMUSG00000076916;ENSMUSG00000076917;ENSMUSG00000076918;ENSMUSG00000076919;ENSMUSG00000076920;ENSMUSG00000076921;ENSMUSG00000076922;ENSMUSG00000076923;ENSMUSG00000076924;ENSMUSG00000076925;ENSMUSG00000076926;ENSMUSG00000076927;ENSMUSG00000076928;ENSMUSG00000076928;ENSMUSG00000089469;ENSMUSG00000090494;ENSMUSG00000090574;ENSMUSG00000090782;ENSMUSG00000091005;ENSMUSG00000091326;ENSMUSG00000096176;ENSMUSG00000096749;ENSMUSG00000096749;ENSMUSG00000104658;ENSMUSG00000104658;ENSMUSG00000104876;ENSMUSG00000105216;ENSMUSG00000105294;ENSMUSG00000105501;ENSMUSG00000105667;ENSMUSG00000105703;ENSMUSG00000106112
  flank_gene_distances
1 0;0;0;0;41103;0;-211
2 183560;191799;184316;158267;172054;-134941;-134941;-135145;28204;28014;-28288;-28314;-33332;-33373;-33379;-33407;-37076;-37381;57025;147396;99163;85522;-73007;66168;66168;65021;63796;63794;63038;59657;56985;56062;54711;53615;53615;52493;52492;49965;49473;48611;47559;46528;46030;44380;42339;41727;40783;38527;37602;36943;36200;34406;32435;31355;30640;29998;27811;27486;26663;26220;25053;23511;22860;21915;21524;20526;19167;17879;17190;16560;15748;15162;12908;12383;10831;9613;8524;6010;5009;4465;3487;0;0;105247;39899;67296;66368;60862;60311;100075;108833;108833;-96959;-96906;79450;50501;98423;125736;-108317;71443;0
3 84742;84668;83131;84684;-145;-297;-304;-309;-309;-319;-332;-359;-394;-28425;-43888;158159;134467;-76224;-117435;-85284
4 -20241;-20293;-20317;-20322;-20291;68458;68458;68457;48588;-137227;-137255;-52109;-52110;0;0;0;0;0;-92357;-95918;112418;-81188;0;102214;0;0;0;103505;12000;52033;52080;49970;-4979;-58411;85959;95738;-100015
5 0;0
6 184860;193099;185616;159567;173354;-136241;-136241;-136445;29504;29314;-29588;-29614;-34632;-34673;-34679;-34707;-38376;-38681;58325;149296;101063;87422;-74907;68068;68068;66921;65696;65694;64938;61557;58885;57962;56611;55515;55515;54393;54392;51865;51373;50511;49459;48428;47930;46280;44239;43627;42683;40427;39502;38843;38100;36306;34335;33255;32540;31898;29711;29386;28563;28120;26953;25411;24760;23815;23424;22426;21067;19779;19090;18460;17648;17062;14808;14283;12731;11513;10424;7910;6909;6365;5387;0;0;107147;41799;69196;68268;62762;62211;101975;110733;110733;-98859;-98806;81350;52401;99723;127036;-109617;72743;0

In [7]:
head(cluster1_df[,1:16])

  seqnames start    end      width strand V4         V5       V6 V7
1 14       54223651 54224100  450  *      924.779_r5  3.32921 .  54223650
2 1        64531551 64533300 1750  *      7739.42    13.46730 .  64531550
3 12       98269451 98270700 1250  *      13697.4    24.54790 .  98269450
4 12       98269701 98270550  850  *      2395.18     4.25398 .  98269700
5 12       98269801 98270500  700  *      2242.74     5.49241 .  98269800
6 12       98269751 98270700  950  *      4517.37     7.85629 .  98269750
  V8       V9 V10 V11  V12      V13       annotation
1 54224100 0  1    450 54223645 cluster_1 3' UTR
2 64533300 0  1   1750 64531544 cluster_1 Promoter (<=1kb)
3 98270700 0  1   1250 98269441 cluster_1 Promoter (<=1kb)
4 98270550 0  1    850 98269691 cluster_1 Promoter (1-2kb)
5 98270500 0  1    700 98269791 cluster_1 Promoter (1-2kb)
6 98270700 0  1    950 98269741 cluster_1 Promoter (1-2kb)

In [8]:
# Is V4 unique?
length(unique(cluster1_df$V4)) == nrow(cluster1_df) # TRUE
length(unique(cluster2_df$V4)) == nrow(cluster2_df) # TRUE

[1] TRUE

[1] TRUE

In [9]:
# Is V4 unique across both clusters?
length(unique(c(cluster1_df$V4, cluster2_df$V4))) == (nrow(cluster1_df) + nrow(cluster2_df)) # TRUE

# Combine
peaks <- bind_rows(cluster1_df, cluster2_df)

[1] TRUE

## Convert EnsemblIDs to Gene Symbols+

In [10]:
# Load EnsemblID conversion
ensembl2symbol <- read.table("source_data/ensembl_102.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)
colnames(ensembl2symbol) <- c("GeneID", "GeneSymbol")

# Check df
head(ensembl2symbol)

  GeneID             GeneSymbol
1 ENSMUSG00000064372 mt-Tp
2 ENSMUSG00000064371 mt-Tt
3 ENSMUSG00000064370 mt-Cytb
4 ENSMUSG00000064369 mt-Te
5 ENSMUSG00000064368 mt-Nd6
6 ENSMUSG00000064367 mt-Nd5

In [11]:
# Function to convert EnsemblIDs to GeneSymbols
convert_ids <- function(ids, conversion_df) {
    sapply(ids, function(id) {
        id_list <- unlist(strsplit(id, ";"))
        symbol_list <- sapply(id_list, function(single_id) {
            symbol <- conversion_df$GeneSymbol[conversion_df$GeneID == single_id]
            if (length(symbol) == 0 || is.na(symbol[1]) || symbol[1] == "") {
                return(single_id)
            } else {
                return(symbol)
            }
        })
        paste(symbol_list, collapse = ";")
    })
}

In [12]:
# Keep only items in ensemble2symbol that are in peak_anno_df
uniqueids <- unique(unlist(strsplit(peaks$flank_geneIds, ";")))
uniqueids <- unique(c(uniqueids, peaks$flank_geneId))

ensembl2symbol <- ensembl2symbol[ensembl2symbol$GeneID %in% uniqueids, ]

In [13]:
# Convert geneId and flank_geneIds columns
peaks$geneSymbol <- convert_ids(peaks$geneId, ensembl2symbol)
peaks$flank_geneSymbols <- convert_ids(peaks$flank_geneIds, ensembl2symbol)
print("Done Annotation")

[1] "Done Annotation"

In [14]:
head(peaks)

  seqnames start    end      width strand V4         V5       V6 V7
1 14       54223651 54224100  450  *      924.779_r5  3.32921 .  54223650
2 1        64531551 64533300 1750  *      7739.42    13.46730 .  64531550
3 12       98269451 98270700 1250  *      13697.4    24.54790 .  98269450
4 12       98269701 98270550  850  *      2395.18     4.25398 .  98269700
5 12       98269801 98270500  700  *      2242.74     5.49241 .  98269800
6 12       98269751 98270700  950  *      4517.37     7.85629 .  98269750
  V8       ⋯ geneLength geneStrand geneId             transcriptId
1 54224100 ⋯  3686      1          ENSMUSG00000076928 ENSMUST00000198398
2 64533300 ⋯ 65051      1          ENSMUSG00000025958 ENSMUST00000185594
3 98270700 ⋯  7990      1          ENSMUSG00000021886 ENSMUST00000075072
4 98270550 ⋯  7990      1          ENSMUSG00000021886 ENSMUST00000075072
5 98270500 ⋯  7990      1          ENSMUSG00000021886 ENSMUST00000075072
6 98270700 ⋯  7990      1          ENSMUSG00000021886 ENSMUST00000075072
  distanceToTSS
1 3130
2    0
3  816
4 1066
5 1166
6 1116
  flank_txIds
1 ENSMUST00000000984;ENSMUST00000197440;ENSMUST00000195970;ENSMUST00000196966;ENSMUST00000198107;ENSMUST00000000985;ENSMUST00000196882;ENSMUST00000022781;ENSMUST00000128231;ENSMUST00000180359;ENSMUST00000199338;ENSMUST00000041197;ENSMUST00000197802;ENSMUST00000196699;ENSMUST00000197605;ENSMUST00000199068;ENSMUST00000197807;ENSMUST00000059996;ENSMUST00000103679;ENSMUST00000103682;ENSMUST00000103683;ENSMUST00000103685;ENSMUST00000197589;ENSMUST00000103686;ENSMUST00000103687;ENSMUST00000103688;ENSMUST00000196977;ENSMUST00000103689;ENSMUST00000103690;ENSMUST00000103691;ENSMUST00000103692;ENSMUST00000103693;ENSMUST00000103694;ENSMUST00000199452;ENSMUST00000200046;ENSMUST00000103695;ENSMUST00000103696;ENSMUST00000103697;ENSMUST00000103698;ENSMUST00000103699;ENSMUST00000103700;ENSMUST00000103701;ENSMUST00000103702;ENSMUST00000103703;ENSMUST00000103704;ENSMUST00000103705;ENSMUST00000103706;ENSMUST00000103707;ENSMUST00000103708;ENSMUST00000103709;ENSMUST00000103710;ENSMUST00000103711;ENSMUST00000103712;ENSMUST00000103713;ENSMUST00000103714;ENSMUST00000103715;ENSMUST00000103716;ENSMUST00000103717;ENSMUST00000103718;ENSMUST00000103719;ENSMUST00000103720;ENSMUST00000103721;ENSMUST00000103722;ENSMUST00000103723;ENSMUST00000103724;ENSMUST00000103725;ENSMUST00000103726;ENSMUST00000103727;ENSMUST00000103728;ENSMUST00000103729;ENSMUST00000103730;ENSMUST00000103731;ENSMUST00000103732;ENSMUST00000103733;ENSMUST00000103734;ENSMUST00000103735;ENSMUST00000103736;ENSMUST00000103737;ENSMUST00000103738;ENSMUST00000103739;ENSMUST00000103740;ENSMUST00000198398;ENSMUST00000158844;ENSMUST00000167829;ENSMUST00000165025;ENSMUST00000167781;ENSMUST00000170585;ENSMUST00000165071;ENSMUST00000177564;ENSMUST00000196221;ENSMUST00000179664;ENSMUST00000198124;ENSMUST00000197620;ENSMUST00000196323;ENSMUST00000197949;ENSMUST00000196803;ENSMUST00000200008;ENSMUST00000196637;ENSMUST00000199958;ENSMUST00000196615
2 ENSMUST00000114079;ENSMUST00000053469;ENSMUST00000162806;ENSMUST00000161264;ENSMUST00000185594;ENSMUST00000171164;ENSMUST00000188855;ENSMUST00000187811;ENSMUST00000049932;ENSMUST00000087366;ENSMUST00000186335;ENSMUST00000190876;ENSMUST00000190348;ENSMUST00000187035;ENSMUST00000190979;ENSMUST00000150749;ENSMUST00000175487;ENSMUST00000187877;ENSMUST00000189284;ENSMUST00000186895
3 ENSMUST00000021390;ENSMUST00000075072
4 ENSMUST00000021390;ENSMUST00000075072
5 ENSMUST00000021390;ENSMUST00000075072
6 ENSMUST00000021390;ENSMUST00000075072
  flank_geneIds
1 ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000022174;ENSMUSG00000022174;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000048153;ENSMUSG00000076867;ENSMUSG00000076870;ENSMUSG00000076871;ENSMUSG00000076873;ENSMUSG00000076874;ENSMUSG00000076874;ENSMUSG00000076875;ENSMUSG00000076876;ENSMUSG00000076876;ENSMUSG00000076877;ENSMUSG00000076878;ENSMUSG00000076879;ENSMUSG00000076880;ENSMUSG00000076881;ENSMUSG00000076882;ENSMUSG00000076882;ENSMUSG00000076883;ENSMUSG00000076883;ENSMUSG00000076884;ENSMUSG00000076885;ENSMUSG00000076886;ENSMUSG00000076887;ENSMUSG00000076888;ENSMUSG00000076889;ENSMUSG00000076890;ENSMUSG00000076891;ENSMUSG00000076892;ENSMUSG00000076893;ENSMUSG00000076894;ENSMUSG00000076895;ENSMUSG00000076896;ENSMUSG00000076897;ENSMUSG00000076898;ENSMUSG00000076899;ENSMUSG00000076900;ENSMUSG00000076901;ENSMUSG00000076902;ENSMUSG00000076903;ENSMUSG00000076904;ENSMUSG00000076905;ENSMUSG00000076906;ENSMUSG00000076907;ENSMUSG00000076908;ENSMUSG00000076909;ENSMUSG00000076910;ENSMUSG00000076911;ENSMUSG00000076912;ENSMUSG00000076913;ENSMUSG00000076914;ENSMUSG00000076915;ENSMUSG00000076916;ENSMUSG00000076917;ENSMUSG00000076918;ENSMUSG00000076919;ENSMUSG00000076920;ENSMUSG00000076921;ENSMUSG00000076922;ENSMUSG00000076923;ENSMUSG00000076924;ENSMUSG00000076925;ENSMUSG00000076926;ENSMUSG00000076927;ENSMUSG00000076928;ENSMUSG00000076928;ENSMUSG00000089469;ENSMUSG00000090494;ENSMUSG00000090574;ENSMUSG00000090782;ENSMUSG00000091005;ENSMUSG00000091326;ENSMUSG00000096176;ENSMUSG00000096749;ENSMUSG00000096749;ENSMUSG00000104658;ENSMUSG00000104658;ENSMUSG00000104876;ENSMUSG00000105216;ENSMUSG00000105294;ENSMUSG00000105501;ENSMUSG00000105667;ENSMUSG00000105703;ENSMUSG00000106112
2 ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000087213;ENSMUSG00000093228;ENSMUSG00000099658;ENSMUSG00000100437;ENSMUSG00000101832
3 ENSMUSG00000021003;ENSMUSG00000021886
4 ENSMUSG00000021003;ENSMUSG00000021886
5 ENSMUSG00000021003;ENSMUSG00000021886
6 ENSMUSG00000021003;ENSMUSG00000021886
  flank_gene_distances
1 185360;193599;186116;160067;-136741;-136741;-136945;30004;29814;-30088;-30114;-35132;-35173;-35179;-35207;-38876;-39181;58825;148746;100513;86872;-74357;67518;67518;66371;65146;65144;64388;61007;58335;57412;56061;54965;54965;53843;53842;51315;50823;49961;48909;47878;47380;45730;43689;43077;42133;39877;38952;38293;37550;35756;33785;32705;31990;31348;29161;28836;28013;27570;26403;24861;24210;23265;22874;21876;20517;19229;18540;17910;17098;16512;14258;13733;12181;10963;9874;7360;6359;5815;4837;0;0;106597;41249;68646;67718;62212;61661;101425;110183;110183;-98309;-98256;80800;51851;100223;127536;-110117;73243;-77364
2 83942;83868;82331;83884;0;0;0;0;0;0;0;0;0;-27625;-43088;157359;135217;-76974;-116635;-84484
3 -9992;0
4 -10242;0
5 -10342;0
6 -10292;0
  geneSymbol
1 Trac
2 Creb1
3 Gpr65
4 Gpr65
5 Gpr65
6 Gpr65
  flank_geneSymbols
1 Slc7a7;Slc7a7;Slc7a7;Slc7a7;Oxa1l;Oxa1l;Oxa1l;Dad1;Dad1;Abhd4;Abhd4;Abhd4;Abhd4;Abhd4;Abhd4;Abhd4;Abhd4;Olfr49;Trdv4;Trdj1;Trdj2;Trdv5;Traj59;Traj59;Traj58;Traj57;Traj57;Traj56;Traj53;Traj52;Traj51;Traj50;Traj49;Traj49;Traj48;Traj48;Traj46;Traj45;Traj44;Traj43;Traj42;Traj41;Traj40;Traj39;Traj38;Traj37;Traj35;Traj34;Traj33;Traj32;Traj31;Traj30;Traj29;Traj28;Traj27;Traj26;Traj25;Traj24;Traj23;Traj22;Traj21;Traj20;Traj19;Traj18;Traj17;Traj16;Traj15;Traj14;Traj13;Traj12;Traj11;Traj9;Traj8;Traj7;Traj6;Traj5;Traj4;Traj3;Traj2;Traj1;Trac;Trac;Gm23704;Traj36;Traj61;Traj60;Traj55;Traj54;Trdd2;Trdd1;Trdd1;Gm30275;Gm30275;Trdc;Traj47;Gm43304;5330426L24Rik;Gm3945;Gm43305;Gm43434
2 Mettl21a;Mettl21a;Mettl21a;Mettl21a;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;2810408I11Rik;Gm25748;Gm28980;Gm29152;Gm28982
3 Galc;Gpr65
4 Galc;Gpr65
5 Galc;Gpr65
6 Galc;Gpr65

## Add Motifs

In [15]:
# Load motif extraction results
motifs <- read.table("04_peakAnnotation/motifs", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

head(motifs)

  PostionID  Motif
1 2164.99_r7 Fra1(bZIP),TTGTGAGTCAAC,-87,+,7.193880
2 1992.74_r1 Fra1(bZIP),GGCTGAGTCACA,-96,+,8.155933
3 1992.74_r1 Fra1(bZIP),GCTGAGTCACAG,-84,-,7.899741
4 1907.09_r2 Fra1(bZIP),GGCTGAGTCACA,29,+,8.155933
5 1907.09_r2 Fra1(bZIP),GCTGAGTCACAG,41,-,7.899741
6 2096.8_r12 Fra1(bZIP),GTGTGACTCAGC,-64,+,8.101607

In [16]:
# Collapse motifs by PostionID
motifs <- motifs %>%
    group_by(PostionID) %>%
    summarise(Motif = paste(unique(Motif), collapse = ";"))

library(stringr)

extract_first_field <- function(x) {
    items <- str_split(x, ";")[[1]]              # split into individual motif entries
    first_fields <- sapply(items, function(i) str_split(i, ",")[[1]][1])  # take first field of each
    paste(first_fields, collapse = ",")
}

motifs <- motifs %>%
  mutate(MotifNames = sapply(Motif, extract_first_field))

head(motifs)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               PostionID
Etv2(ETS),GGCAGGAAGGGG,34,-,7.346291                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1000.48
Fos(bZIP),TTCTGATTCATG,10,+,7.560774;BATF(bZIP),TCTGATTCAT,11,+,6.822503;Atf3(bZIP),TCTGATTCATGT,11,+,6.371063;Atf3(bZIP),TTCTGATTCATG,21,-,6.399684;AP-1(bZIP),CTGATTCATG,12,+,7.183402;AP-1(bZIP),TCTGATTCAT,20,-,6.966729;ETS1(ETS),TCAGGAAGCG,-61,+,7.325725;Etv2(ETS),CTCAGGAAGCGT,-51,-,7.413312;Fli1(ETS),TCAGGAAGCG,-52,-,6.369402;RUNX(Runt),TTGTGGTCTA,-42,-,8.585927;RUNX-AML(Runt),GTTGTGGTCT,-52,+,8.793825;RUNX1(Runt),GTTGTGGTCT,-43,-,8.719201;RUNX2(Runt),CGTTGTGGTCTA,-42,-,8.229152;LEF1(HMG),ATTTCAAAGA,75,-,8.033209;STAT5(Stat),ATTTCAAAGAAG,66,+,6.759652;STAT4(Stat),ATTTCAAAGAAG,66,+,6.930327;STAT4(Stat),TTTCAAAGAAGC,78,-,6.777982 1000.48_r1
Etv2(ETS),GTATTTCCGGCT,-89,+,7.842529;Fli1(ETS),TATTTCCGGC,-88,+,7.165203                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1000.48_r2
ETS:RUNX(ETS,Runt),CCCACTTCCTCT,30,-,12.164342;ETS1(ETS),CACTTCCTCT,30,-,10.329378;Etv2(ETS),CCACTTCCTCTT,20,+,8.090231;Fli1(ETS),CACTTCCTCT,21,+,6.461614;RUNX(Runt),TTGACCACAG,-14,+,8.704172;RUNX-AML(Runt),TGACCACAGT,-4,-,7.809191;RUNX2(Runt),TTGACCACAGTG,-14,+,7.930279                                                                                                                                                                                                                                                                                                                                                                                1000.48_r3
RUNX1(Runt),AAGCCACAAG,65,+,7.930638                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1001.68_r1
KLF3(Zf),GAATGGGCGGGGCGA,1,-,10.941397;KLF1(Zf),ATGGGCGGGGCG,-11,+,10.018534;Klf4(Zf),TGGGCGGGGC,-1,-,9.319395;RUNX1(Runt),TAACCTCAGC,90,+,6.917660                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1001.68_r11
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Motif
Etv2(ETS),GGCAGGAAGGGG,34,-,7.346291                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Etv2(ETS),GGCAGGAAGGGG,34,-,7.346291
Fos(bZIP),TTCTGATTCATG,10,+,7.560774;BATF(bZIP),TCTGATTCAT,11,+,6.822503;Atf3(bZIP),TCTGATTCATGT,11,+,6.371063;Atf3(bZIP),TTCTGATTCATG,21,-,6.399684;AP-1(bZIP),CTGATTCATG,12,+,7.183402;AP-1(bZIP),TCTGATTCAT,20,-,6.966729;ETS1(ETS),TCAGGAAGCG,-61,+,7.325725;Etv2(ETS),CTCAGGAAGCGT,-51,-,7.413312;Fli1(ETS),TCAGGAAGCG,-52,-,6.369402;RUNX(Runt),TTGTGGTCTA,-42,-,8.585927;RUNX-AML(Runt),GTTGTGGTCT,-52,+,8.793825;RUNX1(Runt),GTTGTGGTCT,-43,-,8.719201;RUNX2(Runt),CGTTGTGGTCTA,-42,-,8.229152;LEF1(HMG),ATTTCAAAGA,75,-,8.033209;STAT5(Stat),ATTTCAAAGAAG,66,+,6.759652;STAT4(Stat),ATTTCAAAGAAG,66,+,6.930327;STAT4(Stat),TTTCAAAGAAGC,78,-,6.777982 Fos(bZIP),TTCTGATTCATG,10,+,7.560774;BATF(bZIP),TCTGATTCAT,11,+,6.822503;Atf3(bZIP),TCTGATTCATGT,11,+,6.371063;Atf3(bZIP),TTCTGATTCATG,21,-,6.399684;AP-1(bZIP),CTGATTCATG,12,+,7.183402;AP-1(bZIP),TCTGATTCAT,20,-,6.966729;ETS1(ETS),TCAGGAAGCG,-61,+,7.325725;Etv2(ETS),CTCAGGAAGCGT,-51,-,7.413312;Fli1(ETS),TCAGGAAGCG,-52,-,6.369402;RUNX(Runt),TTGTGGTCTA,-42,-,8.585927;RUNX-AML(Runt),GTTGTGGTCT,-52,+,8.793825;RUNX1(Runt),GTTGTGGTCT,-43,-,8.719201;RUNX2(Runt),CGTTGTGGTCTA,-42,-,8.229152;LEF1(HMG),ATTTCAAAGA,75,-,8.033209;STAT5(Stat),ATTTCAAAGAAG,66,+,6.759652;STAT4(Stat),ATTTCAAAGAAG,66,+,6.930327;STAT4(Stat),TTTCAAAGAAGC,78,-,6.777982
Etv2(ETS),GTATTTCCGGCT,-89,+,7.842529;Fli1(ETS),TATTTCCGGC,-88,+,7.165203                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Etv2(ETS),GTATTTCCGGCT,-89,+,7.842529;Fli1(ETS),TATTTCCGGC,-88,+,7.165203
ETS:RUNX(ETS,Runt),CCCACTTCCTCT,30,-,12.164342;ETS1(ETS),CACTTCCTCT,30,-,10.329378;Etv2(ETS),CCACTTCCTCTT,20,+,8.090231;Fli1(ETS),CACTTCCTCT,21,+,6.461614;RUNX(Runt),TTGACCACAG,-14,+,8.704172;RUNX-AML(Runt),TGACCACAGT,-4,-,7.809191;RUNX2(Runt),TTGACCACAGTG,-14,+,7.930279                                                                                                                                                                                                                                                                                                                                                                                ETS:RUNX(ETS,Runt),CCCACTTCCTCT,30,-,12.164342;ETS1(ETS),CACTTCCTCT,30,-,10.329378;Etv2(ETS),CCACTTCCTCTT,20,+,8.090231;Fli1(ETS),CACTTCCTCT,21,+,6.461614;RUNX(Runt),TTGACCACAG,-14,+,8.704172;RUNX-AML(Runt),TGACCACAGT,-4,-,7.809191;RUNX2(Runt),TTGACCACAGTG,-14,+,7.930279
RUNX1(Runt),AAGCCACAAG,65,+,7.930638                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           RUNX1(Runt),AAGCCACAAG,65,+,7.930638
KLF3(Zf),GAATGGGCGGGGCGA,1,-,10.941397;KLF1(Zf),ATGGGCGGGGCG,-11,+,10.018534;Klf4(Zf),TGGGCGGGGC,-1,-,9.319395;RUNX1(Runt),TAACCTCAGC,90,+,6.917660                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            KLF3(Zf),GAATGGGCGGGGCGA,1,-,10.941397;KLF1(Zf),ATGGGCGGGGCG,-11,+,10.018534;Klf4(Zf),TGGGCGGGGC,-1,-,9.319395;RUNX1(Runt),TAACCTCAGC,90,+,6.917660
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               MotifNames
Etv2(ETS),GGCAGGAAGGGG,34,-,7.346291                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Etv2(ETS)
Fos(bZIP),TTCTGATTCATG,10,+,7.560774;BATF(bZIP),TCTGATTCAT,11,+,6.822503;Atf3(bZIP),TCTGATTCATGT,11,+,6.371063;Atf3(bZIP),TTCTGATTCATG,21,-,6.399684;AP-1(bZIP),CTGATTCATG,12,+,7.183402;AP-1(bZIP),TCTGATTCAT,20,-,6.966729;ETS1(ETS),TCAGGAAGCG,-61,+,7.325725;Etv2(ETS),CTCAGGAAGCGT,-51,-,7.413312;Fli1(ETS),TCAGGAAGCG,-52,-,6.369402;RUNX(Runt),TTGTGGTCTA,-42,-,8.585927;RUNX-AML(Runt),GTTGTGGTCT,-52,+,8.793825;RUNX1(Runt),GTTGTGGTCT,-43,-,8.719201;RUNX2(Runt),CGTTGTGGTCTA,-42,-,8.229152;LEF1(HMG),ATTTCAAAGA,75,-,8.033209;STAT5(Stat),ATTTCAAAGAAG,66,+,6.759652;STAT4(Stat),ATTTCAAAGAAG,66,+,6.930327;STAT4(Stat),TTTCAAAGAAGC,78,-,6.777982 Fos(bZIP),BATF(bZIP),Atf3(bZIP),Atf3(bZIP),AP-1(bZIP),AP-1(bZIP),ETS1(ETS),Etv2(ETS),Fli1(ETS),RUNX(Runt),RUNX-AML(Runt),RUNX1(Runt),RUNX2(Runt),LEF1(HMG),STAT5(Stat),STAT4(Stat),STAT4(Stat)
Etv2(ETS),GTATTTCCGGCT,-89,+,7.842529;Fli1(ETS),TATTTCCGGC,-88,+,7.165203                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Etv2(ETS),Fli1(ETS)
ETS:RUNX(ETS,Runt),CCCACTTCCTCT,30,-,12.164342;ETS1(ETS),CACTTCCTCT,30,-,10.329378;Etv2(ETS),CCACTTCCTCTT,20,+,8.090231;Fli1(ETS),CACTTCCTCT,21,+,6.461614;RUNX(Runt),TTGACCACAG,-14,+,8.704172;RUNX-AML(Runt),TGACCACAGT,-4,-,7.809191;RUNX2(Runt),TTGACCACAGTG,-14,+,7.930279                                                                                                                                                                                                                                                                                                                                                                                ETS:RUNX(ETS,ETS1(ETS),Etv2(ETS),Fli1(ETS),RUNX(Runt),RUNX-AML(Runt),RUNX2(Runt)
RUNX1(Runt),AAGCCACAAG,65,+,7.930638                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           RUNX1(Runt)
KLF3(Zf),GAATGGGCGGGGCGA,1,-,10.941397;KLF1(Zf),ATGGGCGGGGCG,-11,+,10.018534;Klf4(Zf),TGGGCGGGGC,-1,-,9.319395;RUNX1(Runt),TAACCTCAGC,90,+,6.917660                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            KLF3(Zf),KLF1(Zf),Klf4(Zf),RUNX1(Runt)

In [17]:
# Left join motifs to peaks, use V4 in peaks and PostionID in motifs
peaks <- left_join(peaks, motifs, by = c("V4" = "PostionID"))
head(peaks)

  seqnames start    end      width strand V4         V5       V6 V7
1 14       54223651 54224100  450  *      924.779_r5  3.32921 .  54223650
2 1        64531551 64533300 1750  *      7739.42    13.46730 .  64531550
3 12       98269451 98270700 1250  *      13697.4    24.54790 .  98269450
4 12       98269701 98270550  850  *      2395.18     4.25398 .  98269700
5 12       98269801 98270500  700  *      2242.74     5.49241 .  98269800
6 12       98269751 98270700  950  *      4517.37     7.85629 .  98269750
  V8       ⋯ geneId             transcriptId       distanceToTSS
1 54224100 ⋯ ENSMUSG00000076928 ENSMUST00000198398 3130
2 64533300 ⋯ ENSMUSG00000025958 ENSMUST00000185594    0
3 98270700 ⋯ ENSMUSG00000021886 ENSMUST00000075072  816
4 98270550 ⋯ ENSMUSG00000021886 ENSMUST00000075072 1066
5 98270500 ⋯ ENSMUSG00000021886 ENSMUST00000075072 1166
6 98270700 ⋯ ENSMUSG00000021886 ENSMUST00000075072 1116
  flank_txIds
1 ENSMUST00000000984;ENSMUST00000197440;ENSMUST00000195970;ENSMUST00000196966;ENSMUST00000198107;ENSMUST00000000985;ENSMUST00000196882;ENSMUST00000022781;ENSMUST00000128231;ENSMUST00000180359;ENSMUST00000199338;ENSMUST00000041197;ENSMUST00000197802;ENSMUST00000196699;ENSMUST00000197605;ENSMUST00000199068;ENSMUST00000197807;ENSMUST00000059996;ENSMUST00000103679;ENSMUST00000103682;ENSMUST00000103683;ENSMUST00000103685;ENSMUST00000197589;ENSMUST00000103686;ENSMUST00000103687;ENSMUST00000103688;ENSMUST00000196977;ENSMUST00000103689;ENSMUST00000103690;ENSMUST00000103691;ENSMUST00000103692;ENSMUST00000103693;ENSMUST00000103694;ENSMUST00000199452;ENSMUST00000200046;ENSMUST00000103695;ENSMUST00000103696;ENSMUST00000103697;ENSMUST00000103698;ENSMUST00000103699;ENSMUST00000103700;ENSMUST00000103701;ENSMUST00000103702;ENSMUST00000103703;ENSMUST00000103704;ENSMUST00000103705;ENSMUST00000103706;ENSMUST00000103707;ENSMUST00000103708;ENSMUST00000103709;ENSMUST00000103710;ENSMUST00000103711;ENSMUST00000103712;ENSMUST00000103713;ENSMUST00000103714;ENSMUST00000103715;ENSMUST00000103716;ENSMUST00000103717;ENSMUST00000103718;ENSMUST00000103719;ENSMUST00000103720;ENSMUST00000103721;ENSMUST00000103722;ENSMUST00000103723;ENSMUST00000103724;ENSMUST00000103725;ENSMUST00000103726;ENSMUST00000103727;ENSMUST00000103728;ENSMUST00000103729;ENSMUST00000103730;ENSMUST00000103731;ENSMUST00000103732;ENSMUST00000103733;ENSMUST00000103734;ENSMUST00000103735;ENSMUST00000103736;ENSMUST00000103737;ENSMUST00000103738;ENSMUST00000103739;ENSMUST00000103740;ENSMUST00000198398;ENSMUST00000158844;ENSMUST00000167829;ENSMUST00000165025;ENSMUST00000167781;ENSMUST00000170585;ENSMUST00000165071;ENSMUST00000177564;ENSMUST00000196221;ENSMUST00000179664;ENSMUST00000198124;ENSMUST00000197620;ENSMUST00000196323;ENSMUST00000197949;ENSMUST00000196803;ENSMUST00000200008;ENSMUST00000196637;ENSMUST00000199958;ENSMUST00000196615
2 ENSMUST00000114079;ENSMUST00000053469;ENSMUST00000162806;ENSMUST00000161264;ENSMUST00000185594;ENSMUST00000171164;ENSMUST00000188855;ENSMUST00000187811;ENSMUST00000049932;ENSMUST00000087366;ENSMUST00000186335;ENSMUST00000190876;ENSMUST00000190348;ENSMUST00000187035;ENSMUST00000190979;ENSMUST00000150749;ENSMUST00000175487;ENSMUST00000187877;ENSMUST00000189284;ENSMUST00000186895
3 ENSMUST00000021390;ENSMUST00000075072
4 ENSMUST00000021390;ENSMUST00000075072
5 ENSMUST00000021390;ENSMUST00000075072
6 ENSMUST00000021390;ENSMUST00000075072
  flank_geneIds
1 ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000958;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000000959;ENSMUSG00000022174;ENSMUSG00000022174;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000040997;ENSMUSG00000048153;ENSMUSG00000076867;ENSMUSG00000076870;ENSMUSG00000076871;ENSMUSG00000076873;ENSMUSG00000076874;ENSMUSG00000076874;ENSMUSG00000076875;ENSMUSG00000076876;ENSMUSG00000076876;ENSMUSG00000076877;ENSMUSG00000076878;ENSMUSG00000076879;ENSMUSG00000076880;ENSMUSG00000076881;ENSMUSG00000076882;ENSMUSG00000076882;ENSMUSG00000076883;ENSMUSG00000076883;ENSMUSG00000076884;ENSMUSG00000076885;ENSMUSG00000076886;ENSMUSG00000076887;ENSMUSG00000076888;ENSMUSG00000076889;ENSMUSG00000076890;ENSMUSG00000076891;ENSMUSG00000076892;ENSMUSG00000076893;ENSMUSG00000076894;ENSMUSG00000076895;ENSMUSG00000076896;ENSMUSG00000076897;ENSMUSG00000076898;ENSMUSG00000076899;ENSMUSG00000076900;ENSMUSG00000076901;ENSMUSG00000076902;ENSMUSG00000076903;ENSMUSG00000076904;ENSMUSG00000076905;ENSMUSG00000076906;ENSMUSG00000076907;ENSMUSG00000076908;ENSMUSG00000076909;ENSMUSG00000076910;ENSMUSG00000076911;ENSMUSG00000076912;ENSMUSG00000076913;ENSMUSG00000076914;ENSMUSG00000076915;ENSMUSG00000076916;ENSMUSG00000076917;ENSMUSG00000076918;ENSMUSG00000076919;ENSMUSG00000076920;ENSMUSG00000076921;ENSMUSG00000076922;ENSMUSG00000076923;ENSMUSG00000076924;ENSMUSG00000076925;ENSMUSG00000076926;ENSMUSG00000076927;ENSMUSG00000076928;ENSMUSG00000076928;ENSMUSG00000089469;ENSMUSG00000090494;ENSMUSG00000090574;ENSMUSG00000090782;ENSMUSG00000091005;ENSMUSG00000091326;ENSMUSG00000096176;ENSMUSG00000096749;ENSMUSG00000096749;ENSMUSG00000104658;ENSMUSG00000104658;ENSMUSG00000104876;ENSMUSG00000105216;ENSMUSG00000105294;ENSMUSG00000105501;ENSMUSG00000105667;ENSMUSG00000105703;ENSMUSG00000106112
2 ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025956;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000025958;ENSMUSG00000087213;ENSMUSG00000093228;ENSMUSG00000099658;ENSMUSG00000100437;ENSMUSG00000101832
3 ENSMUSG00000021003;ENSMUSG00000021886
4 ENSMUSG00000021003;ENSMUSG00000021886
5 ENSMUSG00000021003;ENSMUSG00000021886
6 ENSMUSG00000021003;ENSMUSG00000021886
  flank_gene_distances
1 185360;193599;186116;160067;-136741;-136741;-136945;30004;29814;-30088;-30114;-35132;-35173;-35179;-35207;-38876;-39181;58825;148746;100513;86872;-74357;67518;67518;66371;65146;65144;64388;61007;58335;57412;56061;54965;54965;53843;53842;51315;50823;49961;48909;47878;47380;45730;43689;43077;42133;39877;38952;38293;37550;35756;33785;32705;31990;31348;29161;28836;28013;27570;26403;24861;24210;23265;22874;21876;20517;19229;18540;17910;17098;16512;14258;13733;12181;10963;9874;7360;6359;5815;4837;0;0;106597;41249;68646;67718;62212;61661;101425;110183;110183;-98309;-98256;80800;51851;100223;127536;-110117;73243;-77364
2 83942;83868;82331;83884;0;0;0;0;0;0;0;0;0;-27625;-43088;157359;135217;-76974;-116635;-84484
3 -9992;0
4 -10242;0
5 -10342;0
6 -10292;0
  geneSymbol
1 Trac
2 Creb1
3 Gpr65
4 Gpr65
5 Gpr65
6 Gpr65
  flank_geneSymbols
1 Slc7a7;Slc7a7;Slc7a7;Slc7a7;Oxa1l;Oxa1l;Oxa1l;Dad1;Dad1;Abhd4;Abhd4;Abhd4;Abhd4;Abhd4;Abhd4;Abhd4;Abhd4;Olfr49;Trdv4;Trdj1;Trdj2;Trdv5;Traj59;Traj59;Traj58;Traj57;Traj57;Traj56;Traj53;Traj52;Traj51;Traj50;Traj49;Traj49;Traj48;Traj48;Traj46;Traj45;Traj44;Traj43;Traj42;Traj41;Traj40;Traj39;Traj38;Traj37;Traj35;Traj34;Traj33;Traj32;Traj31;Traj30;Traj29;Traj28;Traj27;Traj26;Traj25;Traj24;Traj23;Traj22;Traj21;Traj20;Traj19;Traj18;Traj17;Traj16;Traj15;Traj14;Traj13;Traj12;Traj11;Traj9;Traj8;Traj7;Traj6;Traj5;Traj4;Traj3;Traj2;Traj1;Trac;Trac;Gm23704;Traj36;Traj61;Traj60;Traj55;Traj54;Trdd2;Trdd1;Trdd1;Gm30275;Gm30275;Trdc;Traj47;Gm43304;5330426L24Rik;Gm3945;Gm43305;Gm43434
2 Mettl21a;Mettl21a;Mettl21a;Mettl21a;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;Creb1;2810408I11Rik;Gm25748;Gm28980;Gm29152;Gm28982
3 Galc;Gpr65
4 Galc;Gpr65
5 Galc;Gpr65
6 Galc;Gpr65
  Motif
1 AP-1(bZIP),CCTGATTCAC,-61,-,6.900788;KLF3(Zf),GCAGGGGCGGGGCTT,61,-,10.991785;KLF1(Zf),AGGGGCGGGGCT,49,+,11.178325;KLF1(Zf),GACCCCTCCCCC,87,-,7.900076;Klf4(Zf),GCCGCACCCA,-2,+,8.304291
2 Fli1(ETS),TGCTTCCGCC,45,+,6.518686;Stat3+il21(Stat),GTTTCCAGCAAGTC,89,-,7.269681;Stat3+il21(Stat),TCTTCCCAGCAAAG,-67,-,6.906722;STAT4(Stat),TCTTCCCAGCAA,-80,+,5.737025;STAT4(Stat),GTTTCCAGCAAG,76,+,5.271245;STAT4(Stat),CTTCCCAGCAAA,-68,-,6.157281
3 NA
4 RUNX-AML(Runt),CTTGTGGTTC,65,+,7.475800;RUNX1(Runt),CTTGTGGTTC,74,-,7.175319
5 RUNX-AML(Runt),CTTGTGGTTC,40,+,7.475800;RUNX1(Runt),CTTGTGGTTC,49,-,7.175319
6 RUNX-AML(Runt),CTTGTGGTTC,-35,+,7.475800;RUNX1(Runt),CTTGTGGTTC,-26,-,7.175319
  MotifNames
1 AP-1(bZIP),KLF3(Zf),KLF1(Zf),KLF1(Zf),Klf4(Zf)
2 Fli1(ETS),Stat3+il21(Stat),Stat3+il21(Stat),STAT4(Stat),STAT4(Stat),STAT4(Stat)
3 NA
4 RUNX-AML(Runt),RUNX1(Runt)
5 RUNX-AML(Runt),RUNX1(Runt)
6 RUNX-AML(Runt),RUNX1(Runt)

In [18]:
# Save CSV and RDS
write.csv(peaks, "04_peakAnnotation/peaks_annotated.csv", row.names = FALSE)
saveRDS(peaks, "04_peakAnnotation/peaks_annotated.rds")