# 2026-012 Natural De-Diff D35 Analysis

This notebook details flow cytometry analysis for 2026-012 De-Diff Day 35

## Initialize Environment

In [14]:
# Load Packages
library(fcexpr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(ggsci)
library(stringr)
library(jsonlite)

In [15]:
# Set Working Directory
setwd("/home/dalbao/AlbaoRunx3Manuscript/flow/Fig02")

# Load flow processing functions
source("/home/dalbao/AlbaoRunx3Manuscript/flow/scripts/flowProcessing.R")

# Load Workspace (or cached version if it exists)
workspace <- load_workspace_cached(
                wsp_file = "2026-012-NatRechallenge-Analysis.wsp",
                rds_file = "2026-012-NatRechallenge-Analysis.rds",
                overwrite = FALSE # Set to TRUE to reprocess WSP and overwrite cached workspace
        )

# Extract Counts
counts <- workspace[["counts"]]

# Process Gating Data
Cleanup data to report only gates below CD8.

In [16]:
# Filter only samples in "Samples" FlowJoGroup
surface <- counts %>% filter(grepl("Mix", FlowJoGroup))

# Replace MixA in FlowJoGroup as Mix3
surface$FlowJoGroup <- gsub("MixA", "Mix3", surface$FlowJoGroup)

# Replace _CD8 in FileName with ""
surface$SampleID <- paste0(surface$FlowJoGroup, "_", str_extract(surface$FileName, "\\d(?=\\.fcs)"))

head(surface)

    FileName             PopulationFullPath
268 Samples_Mix2_001.fcs root
269 Samples_Mix2_001.fcs Lymphocytes
270 Samples_Mix2_001.fcs Lymphocytes/Single Cells
271 Samples_Mix2_001.fcs Lymphocytes/Single Cells/Lymphocytes
272 Samples_Mix2_001.fcs Lymphocytes/Single Cells/Single Cells
273 Samples_Mix2_001.fcs Lymphocytes/Single Cells/Single Cells/CD8
    Parent                                Population                Count
268 NA                                    root                      6182667
269 root                                  NA/Lymphocytes            5053513
270 Lymphocytes                           Lymphocytes/Single Cells  4379196
271 Lymphocytes/Single Cells              Single Cells/Lymphocytes  4379196
272 Lymphocytes/Single Cells              Single Cells/Single Cells 3985229
273 Lymphocytes/Single Cells/Single Cells CD8                       2115097
    ParentCount FractionOfParent xDim            yDim           eventsInside
268      NA            NA        NA              NA             NA
269 6182667     0.8173678        FSC-A           SSC-A          1
270 5053513     0.8665647        FSC-W           FSC-H          1
271 4379196     1.0000000        FSC-A           SSC-A          1
272 4379196     0.9100367        SSC-W           SSC-H          1
273 3985229     0.5307341        Comp-PE W_561-A Comp-BUV 396-A 1
    FilePath
268 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
269 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
270 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
271 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
272 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
273 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
    FlowJoGroup ws              SampleID
268 Mix2        09-Jun-2026.wsp Mix2_1
269 Mix2        09-Jun-2026.wsp Mix2_1
270 Mix2        09-Jun-2026.wsp Mix2_1
271 Mix2        09-Jun-2026.wsp Mix2_1
272 Mix2        09-Jun-2026.wsp Mix2_1
273 Mix2        09-Jun-2026.wsp Mix2_1

Process df:

In [17]:
# Keep only observations in surface wherin PopulationFullPath contains
# "primary|SP|DP"
surface <- surface %>%
    filter(grepl("primary|SP|DP", PopulationFullPath))

# Remove "secondary/"
surface <- surface %>%
    mutate(PopulationFullPath = gsub("secondary/", "", PopulationFullPath))

# Remove "Lymphocytes/Single Cells/Single Cells/CD8/" from PopulationFullPath
surface <- surface %>%
    mutate(PopulationFullPath = gsub("Lymphocytes/Single Cells/Single Cells/CD8/", "", PopulationFullPath))

head(surface)

    FileName             PopulationFullPath
274 Samples_Mix2_001.fcs primary
277 Samples_Mix2_001.fcs primary/63-3
278 Samples_Mix2_001.fcs primary/63-6
279 Samples_Mix2_001.fcs primary/63-63
280 Samples_Mix2_001.fcs primary/63-DN
281 Samples_Mix2_001.fcs primary/A
    Parent                                            Population    Count
274 Lymphocytes/Single Cells/Single Cells/CD8         primary       143564
277 Lymphocytes/Single Cells/Single Cells/CD8/primary primary/63-3   46895
278 Lymphocytes/Single Cells/Single Cells/CD8/primary primary/63-6   12476
279 Lymphocytes/Single Cells/Single Cells/CD8/primary primary/63-63  40647
280 Lymphocytes/Single Cells/Single Cells/CD8/primary primary/63-DN  43546
281 Lymphocytes/Single Cells/Single Cells/CD8/primary primary/A      14772
    ParentCount FractionOfParent xDim               yDim          eventsInside
274 2115097     0.06787585       Comp-PerCP Cy5-5-A Comp-BUV496-A 1
277  143564     0.32664874       Comp-PE-Cy7-A      Comp-BV510-A  1
278  143564     0.08690201       Comp-PE-Cy7-A      Comp-BV510-A  1
279  143564     0.28312808       Comp-PE-Cy7-A      Comp-BV510-A  1
280  143564     0.30332117       Comp-PE-Cy7-A      Comp-BV510-A  1
281  143564     0.10289488       Comp-BV650-A       Comp-PE-Cy7-A 1
    FilePath
274 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
277 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
278 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
279 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
280 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
281 /D:/UF%20Dropbox/SCRPS-PipkinLab/Dominic%20Albao/Experiments/2026-012%20FateMappingTest/2026-012-RechallengeD35+7/Samples_Mix2_001.fcs
    FlowJoGroup ws              SampleID
274 Mix2        09-Jun-2026.wsp Mix2_1
277 Mix2        09-Jun-2026.wsp Mix2_1
278 Mix2        09-Jun-2026.wsp Mix2_1
279 Mix2        09-Jun-2026.wsp Mix2_1
280 Mix2        09-Jun-2026.wsp Mix2_1
281 Mix2        09-Jun-2026.wsp Mix2_1

In [18]:
# Select relevant columns
surface <- surface %>%
    select(SampleID, FlowJoGroup, PopulationFullPath, Count, FractionOfParent) %>% 
    # Rename FractionOfParent to Percent
    rename(Percent = FractionOfParent, Mix = FlowJoGroup) %>% # mutate
    mutate(Percent = Percent * 100) # Convert to percentage
    # Renme SampleID to ID
surface <- surface %>% rename(ID = SampleID)

# Preview
head(surface)

    ID     Mix  PopulationFullPath Count  Percent
274 Mix2_1 Mix2 primary            143564  6.787585
277 Mix2_1 Mix2 primary/63-3        46895 32.664874
278 Mix2_1 Mix2 primary/63-6        12476  8.690201
279 Mix2_1 Mix2 primary/63-63       40647 28.312808
280 Mix2_1 Mix2 primary/63-DN       43546 30.332117
281 Mix2_1 Mix2 primary/A           14772 10.289488

Calculate total percent:

In [19]:
# Without rounding at all
total_percent <- compute_percent_of_total(surface) %>%
    add_population_derivatives() %>%
    finalize_flow_table(round_digits = NULL)

head(total_percent, n = 10)

   ID     Population Population1Deriv Mix  Count Percent     PercentOfTotal
1  Mix2_1 DP         NA               Mix2 4140  95.04132231 95.04132231
2  Mix2_1 DP         63-3             Mix2  201   4.85507246  4.61432507
3  Mix2_1 DP         63-6             Mix2  872  21.06280193 20.01836547
4  Mix2_1 DP         63-63            Mix2  222   5.36231884  5.09641873
5  Mix2_1 DP         63-DN            Mix2 2845  68.71980676 65.31221304
6  Mix2_1 DP         A                Mix2 1240  29.95169082 28.46648301
7  Mix2_1 DP         B                Mix2 1629  39.34782609 37.39669421
8  Mix2_1 DP         C                Mix2   75   1.81159420  1.72176309
9  Mix2_1 DP         D                Mix2    4   0.09661836  0.09182736
10 Mix2_1 DP         Gerlach-Hi       Mix2 3310  79.95169082 75.98714417

In [20]:
interesting <- total_percent %>%
    filter((grepl("Gerlach", Population1Deriv))) %>%
    mutate(Population1Deriv = factor(gsub("Gerlach-", "", Population1Deriv), levels = c("Lo", "Int", "Hi")))

In [21]:
interesting

   ID     Population Population1Deriv Mix  Count Percent    PercentOfTotal
1  Mix2_1 DP         Hi               Mix2  3310 79.9516908 75.9871442
2  Mix2_1 DP         Int              Mix2   701 16.9323671 16.0927456
3  Mix2_1 DP         Lo               Mix2    40  0.9661836  0.9182736
4  Mix2_1 SP         Hi               Mix2    27 28.7234043  0.6198347
5  Mix2_1 SP         Int              Mix2    41 43.6170213  0.9412305
6  Mix2_1 SP         Lo               Mix2    10 10.6382979  0.2295684
7  Mix2_1 primary    Hi               Mix2 29166 20.3156780  1.3789438
8  Mix2_1 primary    Int              Mix2 77897 54.2594244  3.6829044
9  Mix2_1 primary    Lo               Mix2 24032 16.7395726  1.1362127
10 Mix2_2 DP         Hi               Mix2  1825 94.3152455 51.6704417
11 Mix2_2 DP         Int              Mix2    75  3.8759690  2.1234428
12 Mix2_2 DP         Lo               Mix2     8  0.4134367  0.2265006
13 Mix2_2 SP         Hi               Mix2   926 59.4351733 26.2174405
14 Mix2_2 SP         Int              Mix2   444 28.4980745 12.5707814
15 Mix2_2 SP         Lo               Mix2    64  4.1078306  1.8120045
16 Mix2_2 primary    Hi               Mix2 11524 19.3320025  0.6004285
17 Mix2_2 primary    Int              Mix2 30861 51.7706464  1.6079333
18 Mix2_2 primary    Lo               Mix2 10462 17.5504521  0.5450957
19 Mix2_3 DP         Hi               Mix2  1207 93.1327160 53.7160659
20 Mix2_3 DP         Int              Mix2    55  4.2438272  2.4477081
21 Mix2_3 DP         Lo               Mix2     9  0.6944444  0.4005340
22 Mix2_3 SP         Hi               Mix2   572 61.8378378 25.4561638
23 Mix2_3 SP         Int              Mix2   251 27.1351351 11.1704495
24 Mix2_3 SP         Lo               Mix2    34  3.6756757  1.5131286
25 Mix2_3 primary    Hi               Mix2  7060 19.7792346  0.4522287
26 Mix2_3 primary    Int              Mix2 18499 51.8266375  1.1849545
27 Mix2_3 primary    Lo               Mix2  6275 17.5799854  0.4019455
28 Mix2_4 DP         Hi               Mix2 10092 82.6264942 38.0772714
29 Mix2_4 DP         Int              Mix2  1630 13.3453414  6.1500151
30 Mix2_4 DP         Lo               Mix2   140  1.1462256  0.5282222
⋮  ⋮      ⋮          ⋮                ⋮    ⋮     ⋮          ⋮
43 Mix3_1 primary    Hi               Mix3 11945 60.146022   1.22573290
44 Mix3_1 primary    Int              Mix3  5129 25.825780   0.52631093
45 Mix3_1 primary    Lo               Mix3  1833  9.229607   0.18809279
46 Mix3_2 DP         Hi               Mix3 11985 51.504083  48.71753181
47 Mix3_2 DP         Int              Mix3  7881 33.867641  32.03528312
48 Mix3_2 DP         Lo               Mix3  1210  5.199828   4.91849925
49 Mix3_2 SP         Hi               Mix3   891 79.767234   3.62180399
50 Mix3_2 SP         Int              Mix3   154 13.786929   0.62599081
51 Mix3_2 SP         Lo               Mix3    18  1.611459   0.07316776
52 Mix3_2 primary    Hi               Mix3 22592 29.402501   1.50023740
53 Mix3_2 primary    Int              Mix3 36019 46.877156   2.39186663
54 Mix3_2 primary    Lo               Mix3 10626 13.829275   0.70562689
55 Mix3_3 DP         Hi               Mix3 52001 66.741536  65.35744809
56 Mix3_3 DP         Int              Mix3 16932 21.731653  21.28098135
57 Mix3_3 DP         Lo               Mix3  3080  3.953076   3.87109748
58 Mix3_3 SP         Hi               Mix3   721 78.970427   0.90618873
59 Mix3_3 SP         Int              Mix3    83  9.090909   0.10431854
60 Mix3_3 SP         Lo               Mix3    25  2.738226   0.03142125
61 Mix3_3 primary    Hi               Mix3 30265 28.812559   1.51441534
62 Mix3_3 primary    Int              Mix3 54255 51.651260   2.71483907
63 Mix3_3 primary    Lo               Mix3 11836 11.267981   0.59225574
64 Mix3_4 DP         Hi               Mix3  4708 60.289410  59.28724342
65 Mix3_4 DP         Int              Mix3  2136 27.353054  26.89837552
66 Mix3_4 DP         Lo               Mix3   394  5.045460   4.96159174
67 Mix3_4 SP         Hi               Mix3    30 83.333333   0.37778617
68 Mix3_4 SP         Int              Mix3     2  5.555556   0.02518574
69 Mix3_4 SP         Lo               Mix3     1  2.777778   0.01259287
70 Mix3_4 primary    Hi               Mix3 14243 21.647871   0.99058585
71 Mix3_4 primary    Int              Mix3 31718 48.208043   2.20595395
72 Mix3_4 primary    Lo               Mix3 13303 20.219169   0.92520983

## Plot

In [22]:
# Use theme_bw, base 12, not bold, and remove legend
theme <- theme_bw(
    base_size = 14,
    base_family = "sans"
) +
    theme(
        axis.text = element_text(size = 14, color = "black"),
        axis.title = element_text(size = 14, color = "black"),
        axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5, color = "black"),
        axis.text.y = element_text(size = 12, color = "black"),
        axis.title.x = element_blank(),

        # Remove facet strip background + box
        strip.background = element_rect(fill = NA, color = NA),
        strip.text = element_text(color = "black"),  # optional: keep text styling clean

        legend.position = "none",
        plot.title = element_text(size = 12),
        panel.grid = element_blank()
    )

In [23]:
comparisons <- list(
    c("SP", "DP"),
    c("SP", "primary"),
    c("DP", "primary")
)

mix_ident <- list(

    Mix2 = c(SP = "b", DP = "c", primary  = "d"),
    Mix3 = c(SP = "c", DP = "a", primary  = "d")

)

cols = c(a = "#1D2B53", b = "#7E2553", c = "#FF004D", d = "#FFFFFF")

In [24]:
for(mix in c("Mix2", "Mix3")){

    # If Population1Deriv is NA, change value to "all"
    plot.data.df <- interesting %>% filter(Mix == mix & Population != "all")

    plot.data.df <- plot.data.df %>% 
        mutate( 
                # Replace SP and DP in Population column with mix_ident values
                Population = factor(    Population, levels = c("SP", "DP", "primary"),
                                        labels = c(mix_ident[[mix]]["SP"], mix_ident[[mix]]["DP"], mix_ident[[mix]]["primary"])
                )
        )

    # Ensure paired samples line up correctly: plot_padj()/rstatix pair rows
    # POSITIONALLY (i-th row of group1 with i-th row of group2 as they appear
    # in the data), NOT by ID. Sorting by ID within each facet guarantees
    # both Population groups are in the same ID order, so position == animal.
    plot.data.df <- plot.data.df %>% arrange("Population1Deriv", ID)

    # comparisons is defined in terms of "SP"/"DP", but Population has just been
    # relabeled to this mix's letter codes above, so translate it through
    # mix_ident too, or plot_padj() filters on labels that no longer exist
    # in the data (empty x/y vectors -> t.test "not enough 'x' observations")
    comparisons_mix <- lapply(comparisons, function(x) unname(mix_ident[[mix]][x]))

    # Calculate p-values and adjusted p-values for comparisons using plot_padj function
    plot.stat.df <- plot_padj(
        data = plot.data.df,
        comparisons = comparisons_mix,
        id_col = "ID",
        y_col = "Percent",
        x_col = "Population",
        facet_col = "Population1Deriv",
        # pool_sd = TRUE,
        paired = TRUE,
        step_fraction = 0.1,
        min_step = 0.5
    )
    # Save plot.stat.df to a CSV file for inspection
    write.csv(plot.stat.df, paste0("2026-012-Fig02g-", mix, "rechallenge.csv"))

    # Round plot.stat.df column foldmean to one significant digit
    # Then concatenate to p.adj.signif only if not "ns", into column p.adj.fold
    plot.stat.df <- plot.stat.df %>%
        mutate(foldmeanround = signif(foldmean, digits = 2)) %>%
        mutate(p.adj.fold = ifelse(p.adj.signif == "ns", "ns", paste0(p.adj.signif, " (", foldmeanround, "x)")))

    # Only the significant comparisons get a bracket drawn (see
    # stat_pvalue_manual below), so only these need extra headroom
    plot.stat.sig <- plot.stat.df %>% filter(p.adj < 0.05)

    # Create the plot
    p <- ggplot(plot.data.df, aes(x = Population, y = Percent, fill = Population)) +
        geom_boxplot(outlier.shape = NA) +
        # Connect each subject's SP and DP points to identify paired samples
        geom_line(aes(group = ID), color = "black", linewidth = 0.5) +
        geom_point(size = 2) +
        facet_wrap(~ Population1Deriv, ncol = 3, scales = "free_y") +
        theme +
        scale_fill_manual(values = cols) +
        # Make room for the p-value bracket: with scales = "free_y", each panel
        # auto-scales to plot.data.df alone, so the bracket drawn at y.position
        # (above the tallest box, per plot_padj()'s step_fraction/min_step) would
        # get clipped at the top of the panel without this. geom_blank() is
        # invisible but still trains the y-scale, and a small multiplier adds
        # headroom for the label text sitting above the bracket line itself.
        geom_blank( data = plot.stat.sig, aes(x = group1, y = y.position),
                    inherit.aes = FALSE) +
        scale_y_continuous(expand = expansion(mult = c(0.05, 0.35))) +
        stat_pvalue_manual(
            plot.stat.sig,
            label = "p.adj.fold",   # adjusted p-value stars
            tip.length = 0.05,
            size = 4,
            inherit.aes = FALSE       # important fix
        ) +
        theme (  axis.text.x = element_text(angle = 0),
                    strip.text = element_blank(),
                    strip.background = element_blank())
                
    pdf(file =  paste0("2026-012-Fig02g-", mix, "rechallenge.pdf"), width = 4, height = 1.7)
    print(p)
    dev.off()
}

In [25]:
combineMixes <- interesting %>% filter(Population != "all") %>%
    mutate(Group =  ifelse(Population == "primary", "d",
                        ifelse(Mix == "Mix2" & Population == "SP", "b",
                            ifelse(Mix == "Mix3" & Population == "DP", "a", "c")
                        )
                    )) %>% mutate(Group = factor(Group, levels = c("a", "b", "c", "d")))
combineMixes

   ID     Population Population1Deriv Mix  Count Percent    PercentOfTotal
1  Mix2_1 DP         Hi               Mix2  3310 79.9516908 75.9871442
2  Mix2_1 DP         Int              Mix2   701 16.9323671 16.0927456
3  Mix2_1 DP         Lo               Mix2    40  0.9661836  0.9182736
4  Mix2_1 SP         Hi               Mix2    27 28.7234043  0.6198347
5  Mix2_1 SP         Int              Mix2    41 43.6170213  0.9412305
6  Mix2_1 SP         Lo               Mix2    10 10.6382979  0.2295684
7  Mix2_1 primary    Hi               Mix2 29166 20.3156780  1.3789438
8  Mix2_1 primary    Int              Mix2 77897 54.2594244  3.6829044
9  Mix2_1 primary    Lo               Mix2 24032 16.7395726  1.1362127
10 Mix2_2 DP         Hi               Mix2  1825 94.3152455 51.6704417
11 Mix2_2 DP         Int              Mix2    75  3.8759690  2.1234428
12 Mix2_2 DP         Lo               Mix2     8  0.4134367  0.2265006
13 Mix2_2 SP         Hi               Mix2   926 59.4351733 26.2174405
14 Mix2_2 SP         Int              Mix2   444 28.4980745 12.5707814
15 Mix2_2 SP         Lo               Mix2    64  4.1078306  1.8120045
16 Mix2_2 primary    Hi               Mix2 11524 19.3320025  0.6004285
17 Mix2_2 primary    Int              Mix2 30861 51.7706464  1.6079333
18 Mix2_2 primary    Lo               Mix2 10462 17.5504521  0.5450957
19 Mix2_3 DP         Hi               Mix2  1207 93.1327160 53.7160659
20 Mix2_3 DP         Int              Mix2    55  4.2438272  2.4477081
21 Mix2_3 DP         Lo               Mix2     9  0.6944444  0.4005340
22 Mix2_3 SP         Hi               Mix2   572 61.8378378 25.4561638
23 Mix2_3 SP         Int              Mix2   251 27.1351351 11.1704495
24 Mix2_3 SP         Lo               Mix2    34  3.6756757  1.5131286
25 Mix2_3 primary    Hi               Mix2  7060 19.7792346  0.4522287
26 Mix2_3 primary    Int              Mix2 18499 51.8266375  1.1849545
27 Mix2_3 primary    Lo               Mix2  6275 17.5799854  0.4019455
28 Mix2_4 DP         Hi               Mix2 10092 82.6264942 38.0772714
29 Mix2_4 DP         Int              Mix2  1630 13.3453414  6.1500151
30 Mix2_4 DP         Lo               Mix2   140  1.1462256  0.5282222
⋮  ⋮      ⋮          ⋮                ⋮    ⋮     ⋮          ⋮
43 Mix3_1 primary    Hi               Mix3 11945 60.146022   1.22573290
44 Mix3_1 primary    Int              Mix3  5129 25.825780   0.52631093
45 Mix3_1 primary    Lo               Mix3  1833  9.229607   0.18809279
46 Mix3_2 DP         Hi               Mix3 11985 51.504083  48.71753181
47 Mix3_2 DP         Int              Mix3  7881 33.867641  32.03528312
48 Mix3_2 DP         Lo               Mix3  1210  5.199828   4.91849925
49 Mix3_2 SP         Hi               Mix3   891 79.767234   3.62180399
50 Mix3_2 SP         Int              Mix3   154 13.786929   0.62599081
51 Mix3_2 SP         Lo               Mix3    18  1.611459   0.07316776
52 Mix3_2 primary    Hi               Mix3 22592 29.402501   1.50023740
53 Mix3_2 primary    Int              Mix3 36019 46.877156   2.39186663
54 Mix3_2 primary    Lo               Mix3 10626 13.829275   0.70562689
55 Mix3_3 DP         Hi               Mix3 52001 66.741536  65.35744809
56 Mix3_3 DP         Int              Mix3 16932 21.731653  21.28098135
57 Mix3_3 DP         Lo               Mix3  3080  3.953076   3.87109748
58 Mix3_3 SP         Hi               Mix3   721 78.970427   0.90618873
59 Mix3_3 SP         Int              Mix3    83  9.090909   0.10431854
60 Mix3_3 SP         Lo               Mix3    25  2.738226   0.03142125
61 Mix3_3 primary    Hi               Mix3 30265 28.812559   1.51441534
62 Mix3_3 primary    Int              Mix3 54255 51.651260   2.71483907
63 Mix3_3 primary    Lo               Mix3 11836 11.267981   0.59225574
64 Mix3_4 DP         Hi               Mix3  4708 60.289410  59.28724342
65 Mix3_4 DP         Int              Mix3  2136 27.353054  26.89837552
66 Mix3_4 DP         Lo               Mix3   394  5.045460   4.96159174
67 Mix3_4 SP         Hi               Mix3    30 83.333333   0.37778617
68 Mix3_4 SP         Int              Mix3     2  5.555556   0.02518574
69 Mix3_4 SP         Lo               Mix3     1  2.777778   0.01259287
70 Mix3_4 primary    Hi               Mix3 14243 21.647871   0.99058585
71 Mix3_4 primary    Int              Mix3 31718 48.208043   2.20595395
72 Mix3_4 primary    Lo               Mix3 13303 20.219169   0.92520983
   Group
1  c
2  c
3  c
4  b
5  b
6  b
7  d
8  d
9  d
10 c
11 c
12 c
13 b
14 b
15 b
16 d
17 d
18 d
19 c
20 c
21 c
22 b
23 b
24 b
25 d
26 d
27 d
28 c
29 c
30 c
⋮  ⋮
43 d
44 d
45 d
46 a
47 a
48 a
49 c
50 c
51 c
52 d
53 d
54 d
55 a
56 a
57 a
58 c
59 c
60 c
61 d
62 d
63 d
64 a
65 a
66 a
67 c
68 c
69 c
70 d
71 d
72 d

In [28]:
comparisons <- list(
    c("a", "b"),
    c("a", "c"),
    c("a", "d"),
    c("b", "c"),
    c("b", "d"),
    c("c", "d")
)

# Calculate p-values and adjusted p-values for comparisons using plot_padj function
plot.stat.df <- plot_padj(
    data = combineMixes,
    comparisons = comparisons,
    y_col = "Percent",
    x_col = "Group",
    facet_col = "Population1Deriv",
    paired = FALSE,
    step_fraction = 0.1,
    min_step = 0.5
)

# Save plot.stat.df to a CSV file for inspection
write.csv(plot.stat.df, paste0("2026-012-EFig04-rechallenge.csv"))

# Round plot.stat.df column foldmean to one significant digit
# Then concatenate to p.adj.signif only if not "ns", into column p.adj.fold
plot.stat.df <- plot.stat.df %>%
    mutate(foldmeanround = signif(foldmean, digits = 2)) %>%
    mutate(p.adj.fold = ifelse(p.adj.signif == "ns", "ns", paste0(p.adj.signif, " (", foldmeanround, "x)")))

# Only the significant comparisons get a bracket drawn (see
# stat_pvalue_manual below), so only these need extra headroom
plot.stat.sig <- plot.stat.df %>% filter(p.adj < 0.05)


# Create the plot
p <- ggplot(combineMixes, aes(x = Group, y = Percent, fill = Group)) +
    geom_boxplot(outlier.shape = NA) +
    # Connect each subject's SP and DP points to identify paired samples
    geom_line(aes(group = ID), color = "black", linewidth = 0.5) +
    geom_point(size = 2) +
    facet_wrap(~ Population1Deriv, ncol = 3, scales = "free_y") +
    theme +
    scale_fill_manual(values = cols) +
    # Make room for the p-value bracket: with scales = "free_y", each panel
    # auto-scales to plot.data.df alone, so the bracket drawn at y.position
    # (above the tallest box, per plot_padj()'s step_fraction/min_step) would
    # get clipped at the top of the panel without this. geom_blank() is
    # invisible but still trains the y-scale, and a small multiplier adds
    # headroom for the label text sitting above the bracket line itself.
    geom_blank( data = plot.stat.sig, aes(x = group1, y = y.position),
                inherit.aes = FALSE) +
    scale_y_continuous(expand = expansion(mult = c(0.05, 0.35))) +
    stat_pvalue_manual(
        plot.stat.sig,
        label = "p.adj.fold",   # adjusted p-value stars
        tip.length = 0.05,
        size = 4,
        inherit.aes = FALSE       # important fix
    ) +
    theme (  axis.text.x = element_text(angle = 0),
                strip.text = element_blank(),
                strip.background = element_blank())
            
pdf(file =  paste0("2026-012-EFig04-rechallenge.pdf"), width = 4, height = 1.7)
print(p)
dev.off()

pdf
  2

In [12]:
interesting <- total_percent %>%
    filter(is.na(Population1Deriv) & Population != "primary")

interesting

   ID     Population Population1Deriv Mix  Count Percent    PercentOfTotal
1  Mix2_1 DP         NA               Mix2  4140 95.0413223 95.0413223
2  Mix2_1 SP         NA               Mix2    94  2.1579431  2.1579431
3  Mix2_2 DP         NA               Mix2  1935 54.7848245 54.7848245
4  Mix2_2 SP         NA               Mix2  1558 44.1109853 44.1109853
5  Mix2_3 DP         NA               Mix2  1296 57.6769025 57.6769025
6  Mix2_3 SP         NA               Mix2   925 41.1659991 41.1659991
7  Mix2_4 DP         NA               Mix2 12214 46.0836100 46.0836100
8  Mix2_4 SP         NA               Mix2 14005 52.8410806 52.8410806
9  Mix3_1 DP         NA               Mix3  3170 95.5394816 95.5394816
10 Mix3_1 SP         NA               Mix3     9  0.2712477  0.2712477
11 Mix3_2 DP         NA               Mix3 23270 94.5896508 94.5896508
12 Mix3_2 SP         NA               Mix3  1117  4.5404658  4.5404658
13 Mix3_3 DP         NA               Mix3 77914 97.9261978 97.9261978
14 Mix3_3 SP         NA               Mix3   913  1.1475039  1.1475039
15 Mix3_4 DP         NA               Mix3  7809 98.3377408 98.3377408
16 Mix3_4 SP         NA               Mix3    36  0.4533434  0.4533434

In [13]:
comparisons <- list(
    c("SP", "DP")
)

mix_ident <- list(

    Mix2 = c(SP = "b", DP = "c"),
    Mix3 = c(SP = "c", DP = "a")

)

cols = c(a = "#1D2B53", b = "#7E2553", c = "#FF004D", d = "#FFFFFF")

In [14]:
for(mix in c("Mix2", "Mix3")){

    # If Population1Deriv is NA, change value to "all"
    plot.data.df <- interesting %>% filter(Mix == mix)

    plot.data.df <- plot.data.df %>% 
        mutate( 
                # Replace SP and DP in Population column with mix_ident values
                Population = factor(    Population, levels = c("SP", "DP"),
                                        labels = c(mix_ident[[mix]]["SP"], mix_ident[[mix]]["DP"])
                )
        )

    # Ensure paired samples line up correctly: plot_padj()/rstatix pair rows
    # POSITIONALLY (i-th row of group1 with i-th row of group2 as they appear
    # in the data), NOT by ID. Sorting by ID within each facet guarantees
    # both Population groups are in the same ID order, so position == animal.
    plot.data.df <- plot.data.df %>% arrange("Population1Deriv", ID)

    # comparisons is defined in terms of "SP"/"DP", but Population has just been
    # relabeled to this mix's letter codes above, so translate it through
    # mix_ident too, or plot_padj() filters on labels that no longer exist
    # in the data (empty x/y vectors -> t.test "not enough 'x' observations")
    comparisons_mix <- lapply(comparisons, function(x) unname(mix_ident[[mix]][x]))

    # Calculate p-values and adjusted p-values for comparisons using plot_padj function
    plot.stat.df <- plot_padj(
        data = plot.data.df,
        comparisons = comparisons_mix,
        id_col = "ID",
        y_col = "Percent",
        x_col = "Population",
        facet_col = "Population1Deriv",
        # pool_sd = TRUE,
        paired = FALSE,
        step_fraction = 0.1,
        min_step = 0.5
    )
    # Save plot.stat.df to a CSV file for inspection
    write.csv(plot.stat.df, paste0("2026-012-Fig02g-", mix, ".ratio_rechallenge.csv"))

    # Round plot.stat.df column foldmean to one significant digit
    # Then concatenate to p.adj.signif only if not "ns", into column p.adj.fold
    plot.stat.df <- plot.stat.df %>%
        mutate(foldmeanround = signif(foldmean, digits = 2)) %>%
        mutate(p.adj.fold = ifelse(p.adj.signif == "ns", "ns", paste0(p.adj.signif, " (", foldmeanround, "x)")))

    # Only the significant comparisons get a bracket drawn (see
    # stat_pvalue_manual below), so only these need extra headroom
    plot.stat.sig <- plot.stat.df %>% filter(p.adj < 0.05)

    # Create the plot
    p <- ggplot(plot.data.df, aes(x = Population, y = Percent, fill = Population)) +
        geom_boxplot(outlier.shape = NA) +
        # Connect each subject's SP and DP points to identify paired samples
        geom_line(aes(group = ID), color = "black", linewidth = 0.5) +
        geom_point(size = 2) +
        facet_wrap(~ Population1Deriv, ncol = 3, scales = "free_y") +
        theme +
        scale_fill_manual(values = cols) +
        # Make room for the p-value bracket: with scales = "free_y", each panel
        # auto-scales to plot.data.df alone, so the bracket drawn at y.position
        # (above the tallest box, per plot_padj()'s step_fraction/min_step) would
        # get clipped at the top of the panel without this. geom_blank() is
        # invisible but still trains the y-scale, and a small multiplier adds
        # headroom for the label text sitting above the bracket line itself.
        geom_blank( data = plot.stat.sig, aes(x = group1, y = y.position),
                    inherit.aes = FALSE) +
        scale_y_continuous(expand = expansion(mult = c(0.05, 0.35))) +
        stat_pvalue_manual(
            plot.stat.sig,
            label = "p.adj.fold",   # adjusted p-value stars
            tip.length = 0.05,
            size = 4,
            inherit.aes = FALSE       # important fix
        ) +
        theme (  axis.text.x = element_text(angle = 0),
                    strip.text = element_blank(),
                    strip.background = element_blank())
                
    pdf(file = paste0("2026-012-Fig02g-", mix, ".ratio_rechallenge.pdf"), width = 1.5, height = 1.7)
    print(p)
    dev.off()
}